### ISSUE TITLE
Enhance README.md to help new users avoid all mail being tagged as unread and inbox

### ISSUE THREAD

**Issue by sten0** [gauteh/lieer#104]
Hi,

Thank you for maintaining gmailieer :-)  I had hoped that following README.md, in consultation with notmuch documentation, would produce a notmuch state similar to my gmail state: ~140 unread, ~5000 inbox, ~50 000 all-mail.  Instead it produced  tagged all ~50 000 as unread and inbox  :-(

Please enhance README.md to help new users avoid all mail being tagged as unread and inbox for the initial sync.

As a bonus I'd appreciate a tip on how to overwrite local state with gmail state to back out of this without deleting and re-initialising, but this second request is just wishlist priority.

Sincerely,
Nicholas

**Comment by sten0** [comment]
Hi @gauteh,

Thanks for the tip!  Yes, `gmi pull --force` did the trick.  You're right, the default new.tags were at fault.  I've begun work on a proposed documentation PR; please keep this issue open and feel free to occasionally ping me if I seem to be taking too long.

Other things I haven't been able to figure out:
  1. Does gmailieer + synchronize_flags do anything useful?  Does it just slow down the synchronisation?  I've seen as low as `10it/s`...but maybe Google is throttling my account because of several `gmi pull -f`?  Maybe it's primarily useful when using gmailieer + notmuch + some other IMAP synchronisation program to migrate off of gmail?
  1. How is the `new` tag useful?  It doesn't seem like I'm losing anything by setting `new.tags` to null.  I thought it might be used in `notmuch new`, but even with the new tag enabled, notmuch outputs `No new mail`, even when there are hundreds of new ones.
  1. In the same way that server-side sieve is now preferred over procmail, I wonder if gmail-side labelling should be used in preference to local notmuch ones, whenever possible, or at least for primary bulk categorisations.
  1.  Tags imported from gmail labels that have spaces in their names are not handled properly by Emacs' `notmuch-mode`, which uses what seems to be an overly restrictive regex schema check (Bug filed against the Debian package).  Renaming "Label Foo" to "label-foo" on the gmail side does not propagate to gmailieer->notmuch for some reason.  I had to delete label, pull, create new label with new name using old rules, and pull to get it to work properly.  In some cases `notmuch new` crashed without this :-(
  1. How does one replicate gmail's "All Mail" view, including SPAM and TRASH, without modifying notmuch's global default to exclude these from searches?  Notmuch's "all mail" appears to be something like `* AND NOT tag:spam AND NOT tag:trash`, yet `* AND tag:spam AND tag:trash` does not produce the desired effect.
  1. It would be nice if gmailieer generated a local-only tag for any unlabelled/archived emails, because gmail frequently (and randomly) unlabels/archives emails.  This can be worked around by https://notmuchmail.org/faq/#index5h2 but it would be more elegant if gmailieer would do it.  Bonus: provides stats for how much gmail is actually messing with your mail ;-)

Sorry for the delay replying, busy week with work.  On the upside, I was able to triage some 10 000 emails and tag ~7 500 for deletion.  Thank you! :-D

**Comment by sten0** [comment]
5.1: `* OR tag:spam OR tag:trash` doesn't do the trick either, presumably because "*" is special, because `tag:spam OR tag:trash` groups NOT-HAM correctly.

**Comment by gauteh** [comment]
You could try and remove the tags from your notmuch config excluded tags and see if that is the problem. These need to be explicitly included. Almost 100% sure we are syncing spam and trash with gmailieer.
