### ISSUE TITLE
Is lieer affected by the "Gmail API lockdown", and if so, how will it be affected

### ISSUE THREAD

**Issue by sten0** [gauteh/lieer#110]
Hi,

I've been enjoying using gmailieer for a few months (sorry I still haven't submitted a PR for the README for new users), and I recently learned of the following possible future issue:

https://arstechnica.com/gadgets/2019/06/gmails-api-lockdown-will-kill-some-third-party-app-access-starting-july-15/
which follows up on
https://cloud.google.com/blog/products/g-suite/elevating-user-trust-in-our-api-ecosystems

For the record, will gmailieer be affected?

Regards,
Nicholas

P.S.  What was the reason for 5f96e82f05a7093d3259c1511ba0b62eedd2739a ?

**Comment by gauteh** [comment]
Check out #100, hopefully all is good!

**Comment by sten0** [comment]
On Sat, Jun 29, 2019 at 10:34:03PM -0700, Gaute Hope wrote:
>    Check out [1]#100, hopefully all is good!
> 

Thanks!  I've filed a bug on the Debian side and linked it to this
one.  Debian 10 (buster) is frozen with gmailieer-0.10.  If an
unfreeze is not possible to accommodate the rename, would
lieer/remote.py:L13 from 5f96e82f05a7093d3259c1511ba0b62eedd2739a
enough to keep it working post-2019-07-15?  Also, will the
gmailieer->lieer github project link/alias be maintained for two
years, or will URLs in the documentation need to be updated asap?

Finally, would you please write migration instructions?  I'm guessing
that the user will need a new "lieer" token to replace their
"gmailieer" one, but will a full resync also be necessary?  Do the old
json files also need to be cleaned up?  Can these files just be
renamed to their lieer equivalents, and will everything "just work"
(eg: no resync required, when the old token stops working it will
prompt the user to get a new one)

Cheers,
Nicholas

**Comment by gauteh** [comment]
No migrations should be necessary, state files will have the old name and the repo alias will exist as long as github allows. I don’t think old versions of gmailieer will stop working, why is it frozen?

**Comment by sten0** [comment]
So the permissions granted using the api key with the "gmailieer" name should continue to work?  I guess we'll find out...  Please keep this issue open until the end of the month ;-)

https://release.debian.org/buster/freeze_policy.html  <- if Google's oath api will begin to deny access to the "gmailieer" application, but will continue to work with "lieer" then a minimal changes targeted fix will be permitted.  That's why I asked if lieer/remote.py:L13 would probably be sufficient :-)

Thanks again for maintaining lieer!

**Comment by gauteh** [comment]
As far as I know the old version with the old application name will continue to work. Otherwise the change should be sufficient.

**Comment by sten0** [comment]
It's good to be wrong sometimes!  Looks like the old version with the old name with the old keys still works :-)  Thanks again for your willingness to discuss how to mitigate the possibility.

**Comment by gauteh** [comment]
Good 😊

man. 22. jul. 2019 kl. 07:39 skrev Nicholas D Steeves <
notifications@github.com>:
