### ISSUE TITLE
How do I donate to you?

### ISSUE THREAD

**Issue by borwick** [gauteh/lieer#111]
I really appreciate lieer! How do I donate to you? Paypal? Venmo? I did not immediately see an option in the README or on http://gaute.vetsj.com/ .

Thanks,
John B.

**Comment by gauteh** [comment]
wow! never though about that! I created an liberapay account: https://liberapay.com/gauteh/ should be possible to use stripe or paypal.

**Comment by gauteh** [comment]
doh, just noticed that is for recurrent donations.. also have paypal: https://www.paypal.me/gauteh

**Comment by gauteh** [comment]
Thanks :) !!
