### ISSUE TITLE
forwarded label

### ISSUE THREAD

**Issue by stdbull** [gauteh/lieer#119]
Hi. I recently noticed that Gmail seems to have started applying the label 'forwarded' to emails that are forwarded (not to the forwarded email itself, but to the original email that has been forwarded - hope that makes sense!). Can you verify this? If so, I guess this should be included in the list of excluded tags/labels that Lieer is aware of (like voicemail, trash, etc). Cheers.

**Comment by gauteh** [comment]
Hi, thanks. I wonder if this matches the `passed` tag from notmuch. Or `P` in maildir flags. So we should probably have a translate there in stead. http://cr.yp.to/proto/maildir.html.

**Comment by gauteh** [comment]
Note that fixing this will trigger some of the issues listed here: https://github.com/gauteh/lieer#changing-ignored-tags-and-translation-after-initial-sync

**Comment by tadfisher** [comment]
I wonder if local state should contain a copy of the config values that are dangerous after initial sync, then it could diff against the static config on push/pull/sync. You could then automatically do a full sync, or refuse to perform the operation and log a warning for the user to fix the situation.

**Comment by gauteh** [comment]
If there is a way to achieve that in a reliable way I think that would be
great.

fre. 4. okt. 2019, 18:27 skrev Tad Fisher <notifications@github.com>:

**Comment by gauteh** [comment]
I don't see this new label in my own emails, anyone else experiencing the same?

**Comment by gauteh** [comment]
Closing, need more information.
