### ISSUE TITLE
Recent frequent failures to pull

### ISSUE THREAD

**Issue by sten0** [gauteh/lieer#120]
Hi @gauteh !

I've been running into the following deal-breaker bug more and more frequently, and I've confirmed it affects both 0.10 and 0.11.  After an undefined period of time it appears to work again, but it doesn't seem to be triggered by frequency of syncs, so I don't think it's some kind of google-side rate-limiting issue.

```
$ gmi --logging_level DEBUG pull
pull: partial synchronization.. (hid: 20177555)
fetching changes: 0it [00:00, ?it/s]remote: no 'history' when more pages were indicated.
remote: request failed, increasing delay between requests to: 1 s
pull: failed, re-try in a bit.
fetching changes: 100it [00:00, 1182.09it/s]
Traceback (most recent call last):
  File "/usr/bin/gmi", line 8, in <module>
    g.main ()
  File "/usr/share/gmailieer/lieer/gmailieer.py", line 155, in main
    args.func (args)
  File "/usr/share/gmailieer/lieer/gmailieer.py", line 351, in pull
    self.partial_pull ()
  File "/usr/share/gmailieer/lieer/gmailieer.py", line 360, in partial_pull
    for hist in self.remote.get_history_since (self.local.state.last_historyId):
  File "/usr/share/gmailieer/lieer/remote.py", line 203, in get_history_since
    raise Remote.NoHistoryException ()
lieer.remote.NoHistoryException
```

Any guidance for how to make this report more useful would be welcome :-)

Cheers,
Nicholas

**Comment by gauteh** [comment]
Hi,

I am considering replacing this with a warning. We've had the hard fail in for ever, and it does not seem that we actually loose any information (even though a user would not necessarily notice that).

I haven't seen any new information from Google about the API behavior here. Any thoughts?

Regards, Gaute

**Comment by gauteh** [comment]
Could you please try #121?

**Comment by gauteh** [comment]
For future reference: https://stackoverflow.com/questions/44276743/gmail-api-users-history-list-returns-nextpagetoken-but-no-history-field

**Comment by sten0** [comment]
@gauteh, Sorry for the horrible delay replying, I'm not sure how these emails slipped past me...  Since Octobre I'd estimate I've encountered this issue...hmm...probably between five and 12 times.  I've read the stackoverflow thread several times, and it leaves me with a feeling of risk...sorry I can't be a better tester, I don't want to risk years of mail going back to Gmails invite-only beta.  Btw, I'm currently using Lieer 1.2.  @julian-klode can we get an ETA for updating the Debian package? (currently has 0.10, #962733 filed 1.5 months ago)

P.S. @gauteh, I still haven't finished coming up with workarounds for the rough edges in Emacs' notmuch, but I am still (slowly) working on that documentation enhancement goal I said I'd work towards ages ago.  Currently the focus is autosaving and autoindexing drafts (like the Gmail web and cell phone interface), while cleaning up the excessive number of (tag:draft AND tag:deleted) entries.  After that's solved, if we still can't sync them with gmail, the next best thing would be two-way sync of the drafts folder and its notmuch index between desktop and laptop--the tools for this already exist, its just a question of testing and documenting it in a central location.

**Comment by nackjicholson** [comment]
This started happening to me a few minutes ago and I've never seen it before. Setting --ignore-empty-history just makes my terminal print `remote: no 'history' when more pages were indicated' repeatedly and it never moves past that.

**Comment by sorend** [comment]
:+1: @nackjicholson -- I have the same issue.

**Comment by clement-buchart** [comment]
Hello, 

I got the `remote: no 'history' when more pages were indicated`, and `--ignore-empty-history` made the terminal loop just like  https://github.com/gauteh/lieer/issues/120#issuecomment-998386425 (after about 4 years of syncing without any issue).

Simply login in to Gmail and moving some mail around and then restarting the pull fixed things for me. Not sure if some previous process got killed (I run gmi in a cron and may have run out of power) or my gmail state managed to get in an unexpected state.

Just leaving this here since it's the best indexed page for this error message. 

Cheers.

**Comment by tschwinge** [comment]
Documenting this here, as the `remote: no 'history' when more pages were indicated` error message points to here.

I've just run into this issue, too.  I've tried to work around via a `gmi pull --limit 1` (described as "Maximum number of messages to pull (soft limit, GMail may return more)"), which I understood to mean number of messages to pull in this `gmi pull` run.  That got me past the error; it retrieved 48 messages -- but it didn't pull *all* missing messages (..., and now just claims that `pull: everything is up-to-date.`).  I've now seen the discussion in #165 etc., which points out issues with `--limit`.  A `gmi pull --force` then completed successfully, and apparently I'm now again fully synchronized, according to comparing this `notmuch dump` with another system's `notmuch dump`.
