### ISSUE TITLE
Is it compatible with other servers?

### ISSUE THREAD

**Issue by vonpupp** [gauteh/lieer#126]
Hello,

I just configured Lieer and it was very easy to setup. I am having some issues with label renaming but I think I still need to try it further to get used to it since it might be a mistake of mine. Congratulations, it looks very promising!

Eventually I would like to ungoogle myself. So I was wondering if gmaileer is compatible with other IMAP servers allowing full by-directional label sync. If so, which ones? If not, this might be an interesting idea worthwhile of consideration.

Thanks.

**Comment by julian-klode** [comment]
It's not, it uses the Gmail API over HTTPS

**Comment by gauteh** [comment]
Thanks, no not it does not support other services. Maybe there are other
services with equivalent apis, but it would require a new tool.

fre. 24. jan. 2020, 23:29 skrev Julian Andres Klode <
notifications@github.com>:

**Comment by vonpupp** [comment]
Thank you both!
