### ISSUE TITLE
some labels not synced (was: newbie help)

### ISSUE THREAD

**Issue by archenemies** [gauteh/lieer#127]
Hello,

I got here following a comment on [this SU question](https://superuser.com/a/1446998/576570).

This project looks great but I'm not an existing notmuch user so I don't know some basic things, and I've been having trouble finding the information I need.

I looked at this document <https://notmuchmail.org/mutttips/> and created my own neomutt config with stuff like this in it:

    virtual-mailboxes \
        "INBOX"     "notmuch://?query=tag:inbox and NOT tag:archive"\
        "Unread"    "notmuch://?query=tag:unread"\
        "Starred"   "notmuch://?query=tag:*"\
        "Sent"      "notmuch://?query=tag:sent"\
        "junk"      "notmuch://?query=tag:junk"\
        "trash"      "notmuch://?query=tag:trash"

However, I don't seem to be able to figure out how to get the same list of spam-filtered messages that I have in Gmail. For example where on the web interface gmail/inbox/primary shows 1 spam, in neomutt the INBOX virtual-mailbox shows 14. This remains true even if I change "NOT tag:archive" to "NOT tag:spam".

Part of the problem is that I don't know how to ask Neomutt what labels are attached to a given message. Is there a standard macro for that? Or a command-line tool? I found an alphabetized list of notmuch commands, but little documentation oriented towards new users.

Also, I couldn't figure out how to create a macro that would let me type a new label by hand. For example if I wanted to change the label of a message to "some_project" for example, by typing the text "some_project" at a readline prompt, is that possible in neomutt? Anyway I got stuck looking for seemingly basic information. Should I be using the Emacs interface instead? Is there a good tutorial for someone who just wants an offline, terminal interface to Gmail?

Thanks.

**Comment by gauteh** [comment]
I think the best option for that is to use [alot](https://alot.readthedocs.io/en/latest/index.html) with [notmuch](https://notmuchmail.org/). The official notmuch client works in emacs, so if you're into that then that is probably the best option. You can also just use the command line notmuch command to search for things, that is probably the easiest way to debug the issue you are seeing. Perhaps it is related to deleted files also showing up in the notmuch query? Try `notmuch search tag:spam` or similar. This tool, and the clients mentioned, are based on notmuch so that is the common denominator that might be worth focusing on.

I tried setting up neomutt myself, but found that it is slow in displaying queries (needs to scan all messages before showing them).

**Comment by archenemies** [comment]
Hmm, `alot` does seem like a very good option, at least it loads quickly and shows the labels.

I think my spam issue is due to the fact that Gmail separates my non-spam Inbox into "Primary", "Social" and "Promotions". All three of these are mixed together when I sync with Gmi. Is there a way to get Gmi to put a special label on Promotions?

Thank you very much for your help.

**Comment by archenemies** [comment]
Here is what I see in Gmail, with "Social", "Promotions", alongside "Primary" in my inbox:

![gmail-interface](https://user-images.githubusercontent.com/12960503/74348358-67671300-4d67-11ea-82eb-b5a05bd77276.png)

I can see these labels here:

    $ gmi pull -t
    ...
    CATEGORY_SOCIAL                CATEGORY_SOCIAL
    CATEGORY_PROMOTIONS            CATEGORY_PROMOTIONS

but nothing like them appears in the output of

    $ notmuch search --output=tags '*'

**Comment by gauteh** [comment]
I think the categories are ignored by default, have a look further down the
readme. But make sure you read the information about changing the setting
in the section further down.

ons. 12. feb. 2020, 16:29 skrev archenemies <notifications@github.com>:

**Comment by archenemies** [comment]
Thank you, that looks like it will solve my problem. Apologies for missing it the first time around.

**Comment by gauteh** [comment]
No worries, hope it works out.

ons. 12. feb. 2020, 21:05 skrev archenemies <notifications@github.com>:
