### ISSUE TITLE
Bad parsing of From header probably caused by <angle brackets> in name part

### ISSUE THREAD

**Issue by jindraj** [gauteh/lieer#132]
One of my contacts changed it's name recently. Gmail shows it well, message in maildir and notmuch looks weird. Neomutt isn't able to display it in the index, but after opening the message in pager it looks the same like in notmuch and maildir file. After a quick discussion of this in #notmuch channel on IRC I believe this issue originates in lieer.

It seems the issue is parsing From header. It doesn't respect that the display-name part is quoted and start parsing addr-spec the like with greedy regex.

- This is what it used to be and looked the same everywhere: on Gmail, in maildir file, in notmuch, in neomutt
```
From: Firstname Lastname <firstnamelastname@exmaple.com>
```

- This is what I can see in Gmail when I display original message:
```
From: "Firstname Lastname <Firstname Lastname >" <firstnamelastname@example.com>
```
- This is what's in the file in maildir:
```
From: "Firstname Lastname" <"Firstname Lastname" <firstnamelastname@example.com>>
 ```
- This is what I can see in `notmuch show id:MSGID`:
```
From: "Firstname Lastname" <"Firstname Lastname" <firstnamelastname@example.com>>
 ```
- This is what I see in neomutt index:
 ```
```
^^ exactly nothing
 
- Opened email in pager:
```
From: "Firstname Lastname" <"Firstname Lastname" <firstnamelastname@example.com>>
```

**Comment by gauteh** [comment]
Hi,

lieer only modifies the raw message by changing line-endings to unix
line-endings (on linux). Otherwise the raw message, as received from
GMail, is not parsed. It is transferred as base64, decoded, line-endings
transformed, and written to file.

I can't think of anywhere in lieer this could be happening.

Regards, Gaute

**Comment by jindraj** [comment]
I did one more check
- imap:
```
From: "Firstname Lastname" <"Firstname Lastname" <firstnamelastname@example.com>>
```

So it seems this probably how it is in Gmail. Just download original shows it differently.

**Comment by gauteh** [comment]
:+1:
