### ISSUE TITLE
gmi send: invalid choice

### ISSUE THREAD

**Issue by mkgvt** [gauteh/lieer#133]
According to https://github.com/gauteh/lieer/blob/master/docs/index.md, `gmi send -C ~/.mail/account.gmail` should send email through Gmail but gmi complains that it is a unknown action:
```
$ gmi send -C ~/.mail/account.gmail
usage: gmi [-h] [--auth_host_name AUTH_HOST_NAME] [--noauth_local_webserver]
           [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
           [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
           {pull,push,sync,auth,init,set} ...
gmi: error: argument action: invalid choice: 'send' (choose from 'pull', 'push', 'sync', 'auth', 'init', 'set')
```
Is the documentation correct and there is a bug in gmi or is gmi correct and there is a bug in the documentation?

**Comment by keegancsmith** [comment]
@mkgvt which version of lieer are you running? You should try run the master branch since the "send" function is not in a tagged release yet.

**Comment by gauteh** [comment]
https://notmuchmail.org/pipermail/notmuch/2020/029334.html

1.1 has been released.
