### ISSUE TITLE
Configuring emacs to use gmailieer rather than sendmail or smtpmail

### ISSUE THREAD

**Issue by mkgvt** [gauteh/lieer#136]
[I would send this to a mailing list if I knew where it was.]

I am so close to getting my ideal email setup working...

Instead of offlineimap or mbsync, I use gmailieer to pull down emails. It is quite fast and I like how well it works with notmuch to map Gmail labels to notmuch tags. Much cleaner than the awkward way of accessing Gmail through IMAP. Where I am stuck is in sending the email.

I could set up smtpmail as described in https://notmuchmail.org/emacstips/#index12h2 but gmailieer recently (v1.1) gained the capability to send mail. I would like to use that if I can so.

Gmailieer sends a draft through Gmail without a problem (once I create a draft using message mode in emacs). Both sending a file and sending from stdin work:
$ gmi send -C path/to/mailbox 1586809748.A123456Z12345.test\:2\,D
$ cat 1586809748.A123456Z12345.test\:2\,D | gmi send -C path/to/mailbox

​But I am stuck configuring emacs to use gmailieer instead of sendmail or smtpmail.el.​ According to the emacs manual, the variable send-mail-function can be set but none of the choices looks appropriate for gmailieer:
https://www.gnu.org/software/emacs/manual/html_node/emacs/Mail-Sending.html

How do I configure emacs to use gmailieer for sending emails?

**Comment by gauteh** [comment]
I follow the notmuch mailinglist, we don't have one for this project. I
don't use emacs, but I think it should work in the same way as msmtp if you
can find examples of that. If you find a solution I think it would be
interesting for many! If there are changes needed it would be great to get
those sorted out.


fre. 17. apr. 2020, 21:49 skrev mkgvt <notifications@github.com>:

**Comment by gauteh** [comment]
Maybe this works, replacing msmtp with gmi send as sendmail program: https://www.emacswiki.org/emacs/GnusMSMTP#toc1

**Comment by gauteh** [comment]
Closing.

**Comment by gauteh** [comment]
See #139 for a relevant discussion.
