### ISSUE TITLE
Personal API key creation process

### ISSUE THREAD

**Issue by kirelagin** [gauteh/lieer#137]
I am trying to create a personal API token, but it wants me to setup an OAuth consent screen, and it is kinda... tricky and seems to require verification.

Either I am missing something, or using a personal API key is not really an option, so it’s better to remove this section from the readme.

**Comment by gauteh** [comment]
It used to depend on what type of app you selected, and whether the key is
for private use/development use or not. The steps and options may have
changed.

søn. 19. apr. 2020, 16:41 skrev Kirill Elagin <notifications@github.com>:

**Comment by kirelagin** [comment]
Ahhh, ok, I tried again and figured it out this time. Basically, it worked, it’s just when I try to authorised using the new client id, it shows a scary page saying that the app was not verified, but there is a tiny button there that allows me to proceed.

------

I documented how I created the key, maybe there should be a wiki page with screenshots...

*  Where will you be calling the API from?  → “Other UI (e.g. Windows, CLI Tool)”.
*  What data will you be accessing?  → “User data”.

After this it says: “Before you can create an OAuth client ID, you must set up an OAuth consent screen to let users know who is requesting access to their data” and a new browser tab opens.

In this new tab it asks me to choose “User Type” with possible options “External” and “Internal (Only available to users within your organization. You will not need to submit your app for verification.)”, but the latter one is unavailable for non-organisations. So I choose “External” and it takes me to a long page where I have to specify OAuth domains and stuff. I enter only the name of application and nothing else, save, and it takes me to a page that shows details about this OAuth application and “ Verification Status: Not published”. 

I close the tab, go back to the previous one, press “Refresh” enter a name for the application (again?), and then it allows me to download the id file.

-------

Also I had to use `gmi auth` with `-f`, otherwise it didn’t seem to have any effect, but the readme doesn’t say this. (Actually, I wonder if it even makes any sense to use `-c` without `-f`.)

**Comment by gauteh** [comment]
Yes, you probably need -f when reauthenthicating a repo that has already
been authorized. Agree with the wiki.

søn. 19. apr. 2020, 17:38 skrev Kirill Elagin <notifications@github.com>:

**Comment by gauteh** [comment]
Closing.

**Comment by flokli** [comment]
@kirelagin did you persist this to the wiki already? I'd also be interested in such a setup :-)

**Comment by kirelagin** [comment]
@flokli I haven’t sorry, I was just too lazy to follow the process again. If you are interested in the setup, maybe you could follow the steps I outlined in my comment above, take screenshots in the process, and that would make a nice complete wiki page.

**Comment by flokli** [comment]
It seems like I won't get to this any time soon. If someone else wants to better document, feel free to do so! :-)
