### ISSUE TITLE
Non ASCII characters not displayed correctly

### ISSUE THREAD

**Issue by imr0** [gauteh/lieer#149]
I sent e-mails via `gmi send` and UTF-8 encoded characters with accents (e.g. éáőú, etc.) in the Subject field end up garbled on the receiving end. The body of the message is unaffected and using e.g. msmtp to send the same mails produced the desired result, therefore I suppose this is some encoding issue with gmailieer.

**Comment by gauteh** [comment]
That could be, gmailieer doesn't do any processing of the message. There
could be something going on with reading from stdin, but thought that
python 3 dealt in utf-8. Decoding the base64 should not cause any problems.
Do you have a copy of the message as it is piped to gmi? It might also be
that google handles it differently depending on whether it comes through
SMTP or through their REST API (they do in other regards, e.g.. grouping
messages automatically with their threads when coming from SMTP).

**Comment by imr0** [comment]
Interesting, I usually use either `alot` or `astroid`. In the end this might be an issue with `alot` as `astroid` sends the e-mail perfectly.
A test message with accented UTF-8 characters that gets piped into `gmi` for example:

alot's case:
```
Content-Type: text/plain; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable
From: Imre Majer <imre.majer@gmail.com>
To: nothing@here.com
Subject: áéúőóü subject
Date: Tue, 12 May 2020 16:57:46 +0200
Message-ID: <158929546601.51509.6310378601074364238@imre-xps13>
User-Agent: alot/0.9

=C3=A1=C3=A9=C3=BA=C5=91=C3=B3=C3=BC body
```
The UTF-8 characters in the subject field remain "áéúőóü" but the body is changed.

astroid's case:
```
Date: Tue, 12 May 2020 17:04:13 +0200
From: Imre Majer <imre.majer@gmail.com>
Subject: =?iso-8859-2?B?4en69fP8?= subject
To: nothing@here.com
MIME-Version: 1.0
User-Agent: astroid/0.15.0 (https://github.com/astroidmail/astroid)
Message-Id: <1589295828.1bsep4hj14.astroid@imre-xps13.none>
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

=C3=A1=C3=A9=C3=BA=C5=91=C3=B3=C3=BC body
```
In this case the encoding of the string "áéúőóü" is changed both in the subject and the body.

I'm not too familiar with what encoding is allowed where but it seems UTF-8 is not liked by gmail in this form.

**Comment by gauteh** [comment]
I think headers are restricted to ASCII when not quoted.

tir. 12. mai 2020, 17:16 skrev imr0 <notifications@github.com>:

**Comment by imr0** [comment]
I see, thank you! Will raise this issue for `alot`'s developer.
