### ISSUE TITLE
Initial pull/sync doesn't tag messages correctly

### ISSUE THREAD

**Issue by dabeeeenster** [gauteh/lieer#156]
Apologies if I missed this in the docs. If I create a new local account and do a first sync, all messages are tagged with `inbox unread`. Am I doing something wrong? Is there a reason lieer doesn't sync the tags correctly on first sync?

**Comment by gauteh** [comment]
What are your notmuch new.tags?

man. 8. jun. 2020, 16:22 skrev Ben Rometsch <notifications@github.com>:

**Comment by dabeeeenster** [comment]
I didn't set any. Was that the issue?

**Comment by gauteh** [comment]
There are some default ones, inbox and unread I think

man. 8. jun. 2020, 17:23 skrev Ben Rometsch <notifications@github.com>:

**Comment by dabeeeenster** [comment]
Is there a way to override the defaults so that the ones present on the server are used?

**Comment by gauteh** [comment]
Yes, you can just remove them from your config. Check the readme.

man. 8. jun. 2020, 17:37 skrev Ben Rometsch <notifications@github.com>:

**Comment by gauteh** [comment]
https://github.com/gauteh/lieer/blob/master/docs/index.md#usage

See step 2 here.

man. 8. jun. 2020, 17:38 skrev Gaute Hope <eg@gaute.vetsj.com>:

**Comment by dabeeeenster** [comment]
Ah perfect thanks.
