### ISSUE TITLE
safe to run simultaneously on multiple computers?

### ISSUE THREAD

**Issue by bbigras** [gauteh/lieer#159]
Is it safe to run `gmi sync` on 2 computers are the same time? I would assume so.

What about if I run `notmuch new` right after `gmi sync` in both case, every time they sync. Could this cause a problem or be a waste of resource since both would try to push the changes?

Right now I'm using a systemd timer to run `gmi sync`.

**Comment by gauteh** [comment]
Yes. It should be safe, but you night loose the changes from one end if done simultaneously on both systems. Notmuch new is not necessary. New messages cannot be added, and lieer keeps the db in sync with files. If you do tagging in notmuch new, they will be done on both, but will only be synced up by first attempt.

**Comment by bbigras** [comment]
Thanks!
