### ISSUE TITLE
Non-GMail account support

### ISSUE THREAD

**Issue by androclus** [gauteh/lieer#160]
Hi Gauteh, et al!

Can lieer work on non-GMail accounts?

REASON I ASK:

lieer plays so well with notmuch and tagging.

isync/mbsync works well for what it does, but it does not translate folders into tags, and does not appear to know anything about notmuch.

Currently, it looks like this:

I would have a folder named, for example, 'Notes' (on a non-GMail, normal IMAP server), and the emails in that folder download (via mbsync), into my local Maildir directory as a subdir called, 'Notes'.

But..

It would be nice to have an option (with lieer or *any* downloader program) to keep the folder structure server-side, but on the local Maildir, just put all mails into one folder (as lieer does) and just tag them.

In my case, 'Notes' folder on server would become a 'notes' notmuch tag locally.

Yes, I know that in notmuch, one can work with searches via 'folder:' instead of 'tag:', but generally, those folders do *not* show up like the tags do, next to each email, in the mail searches (e.g., (inbox unread new)  or (unread notes) ). It would be nice if they did.  Also, it would be nice if I could do '+'s and '-'s on them, etc., like the more powerful tags.

Just curious. Because lieer does such a good job of dealing with the (bastardized IMAP) GMail servers, and successfully passing tags BOTH UP AND DOWN which mbsync does not seem to be able to do. (And because I've seen so many people migrate from offlineimap to mbsync that it hardly seems worth trying offlineimap)..

Any hopes?

Thanks, Gauteh
-Jeff

**Comment by julian-klode** [comment]
Lieer speaks Gmail API, not IMAP. So if you build a server that speaks Gmail api, that would work. I'm not aware of any existing one.

**Comment by gauteh** [comment]
Yes. Lieer uses the Gmail rest API, and not imap. So this is not possible.

søn. 5. jul. 2020, 09:09 skrev Julian Andres Klode <notifications@github.com

**Comment by androclus** [comment]
Well, so much for that.
