### ISSUE TITLE
remote: user rate error, increasing delay to ...

### ISSUE THREAD

**Issue by androclus** [gauteh/lieer#162]
![lieer-gmail-user-rate-error](https://user-images.githubusercontent.com/221629/86968703-76d56700-c121-11ea-9f93-f346d4a008e9.png)
Hi Gaute and everyone..

Whenever I have to do a large sync/push/pull -- such as during initial download, or when I have tagged many (100's, 1000's) messages -- I get a Gmail user rate error message.  (Screenshot attached.)

I see that lieer auto-adjusts, which is a nice feature, and thank you!

However, it still is tedious when Gmail is slowing things down and lieer has to pause.

For instance: The screenshot in this case only shows delays of 1 second. But often -- probably depending on fluctuating Google mail server loads -- lieer has to adjust down to 30 seconds. And either way, I can only pull 50 messages at a time, from an account with over 40,000 emails. This can take hours to complete. (I usually go to bed and check it the next day.)

Is there any way to speed this up, and/or make things go more smoothly, while remaining within Gmail's query/download rates? Perhaps by setting a lieer config?

Thank you,
JS

**Comment by gauteh** [comment]
This tends to become a problem if you do several large syncs either through imap or lieer on the same account. After a few days you will get better rates again. The back off will try to reduce once several requests have gone through successfully, so it is going to stabilize around what Gmail allows. Maybe different granularity fits better, but think this is the advised behavior by google API.

**Comment by gauteh** [comment]
It is still only 1 or 3 seconds, and goes down to 0 again. So it is probably a throttled connection that cause the slow sync, and not delay introduced by lieer.

**Comment by androclus** [comment]
Okay, thanks for the explanation. I'll just hang in there.

Right now, every time I do a 'gmi sync' it takes an hour or two just to 'receive metadata' -- Even if I haven't sent anything new out. Rather frustrating..

Why does it have to go through all 43,000 messages again, taking another hour or 2?

**Comment by androclus** [comment]
Here is a capture of my terminal output of gmi sync. You can see that after about 19%, it keeps going like this, over and over:

0 1 3 7 15 31 15 7 3 1 0 1 3 7 15 31 15 7 3 1 0 1 3 7 15 31 etc...

receiving metadata:   0%|                                                                                       | 51/43309 [00:01<4:30:28,  2.67it/s]remote: could not find remote message: 172f6d66201c6e3d!
receiving metadata:   7%|██████▎                                                                                | 3150/43309 [00:40<09:53, 67.66it/s]remote: user rate error, increasing delay to 1
receiving metadata:   7%|██████▍                                                                                | 3200/43309 [00:40<08:38, 77.38it/s]remote: waiting 1.0 seconds..
remote: user rate error, increasing delay to 3
remote: waiting 3.0 seconds..
remote: user rate error, increasing delay to 7
remote: waiting 7.0 seconds..
remote: user rate error, increasing delay to 15
remote: waiting 15.0 seconds..
receiving metadata:   7%|██████▏                                                                             | 3203/43309 [01:08<30:53:10,  2.77s/it]remote: waiting 15.0 seconds..
receiving metadata:   8%|██████▎                                                                             | 3253/43309 [01:24<22:39:16,  2.04s/it]remote: waiting 15.0 seconds..
receiving metadata:   8%|██████▍                                                                             | 3303/43309 [01:39<16:52:22,  1.52s/it]remote: waiting 15.0 seconds..
receiving metadata:   8%|██████▌                                                                             | 3353/43309 [01:55<12:49:43,  1.16s/it]remote: waiting 15.0 seconds..
receiving metadata:   8%|██████▌                                                                             | 3403/43309 [02:11<10:00:14,  1.11it/s]remote: waiting 15.0 seconds..
receiving metadata:   8%|██████▊                                                                              | 3453/43309 [02:26<8:02:26,  1.38it/s]remote: waiting 15.0 seconds..
receiving metadata:   8%|██████▉                                                                              | 3503/43309 [02:42<6:39:55,  1.66it/s]remote: waiting 15.0 seconds..
receiving metadata:   8%|██████▉                                                                              | 3553/43309 [02:59<5:47:52,  1.90it/s]remote: waiting 15.0 seconds..
receiving metadata:   8%|███████                                                                              | 3603/43309 [03:15<5:05:08,  2.17it/s]remote: waiting 15.0 seconds..
receiving metadata:   8%|███████▏                                                                             | 3653/43309 [03:31<4:36:43,  2.39it/s]remote: waiting 15.0 seconds..
remote: decreasing delay to 7
receiving metadata:   9%|███████▎                                                                             | 3703/43309 [03:47<4:16:47,  2.57it/s]remote: waiting 7.0 seconds..
receiving metadata:   9%|███████▎                                                                             | 3753/43309 [03:54<3:29:31,  3.15it/s]remote: waiting 7.0 seconds..
receiving metadata:   9%|███████▍                                                                             | 3803/43309 [04:02<2:56:21,  3.73it/s]remote: waiting 7.0 seconds..
receiving metadata:   9%|███████▌                                                                             | 3853/43309 [04:09<2:33:01,  4.30it/s]remote: waiting 7.0 seconds..
receiving metadata:   9%|███████▋                                                                             | 3903/43309 [04:17<2:18:05,  4.76it/s]remote: waiting 7.0 seconds..
receiving metadata:   9%|███████▊                                                                             | 3953/43309 [04:25<2:05:58,  5.21it/s]remote: waiting 7.0 seconds..
receiving metadata:   9%|███████▊                                                                             | 4003/43309 [04:32<1:57:36,  5.57it/s]remote: waiting 7.0 seconds..
receiving metadata:   9%|███████▉                                                                             | 4053/43309 [04:40<1:52:13,  5.83it/s]remote: waiting 7.0 seconds..
receiving metadata:   9%|████████                                                                             | 4103/43309 [04:48<1:47:56,  6.05it/s]remote: waiting 7.0 seconds..
receiving metadata:  10%|████████▏                                                                            | 4153/43309 [04:55<1:45:02,  6.21it/s]remote: waiting 7.0 seconds..
receiving metadata:  10%|████████▏                                                                            | 4203/43309 [05:03<1:43:00,  6.33it/s]remote: waiting 7.0 seconds..
remote: decreasing delay to 3
receiving metadata:  10%|████████▎                                                                            | 4253/43309 [05:10<1:41:19,  6.42it/s]remote: waiting 3.0 seconds..
receiving metadata:  10%|████████▍                                                                            | 4303/43309 [05:14<1:26:12,  7.54it/s]remote: waiting 3.0 seconds..
receiving metadata:  10%|████████▌                                                                            | 4353/43309 [05:18<1:13:50,  8.79it/s]remote: waiting 3.0 seconds..
receiving metadata:  10%|████████▋                                                                            | 4403/43309 [05:21<1:06:41,  9.72it/s]remote: waiting 3.0 seconds..
receiving metadata:  10%|████████▋                                                                            | 4453/43309 [05:25<1:00:21, 10.73it/s]remote: waiting 3.0 seconds..
receiving metadata:  10%|█████████                                                                              | 4503/43309 [05:28<55:52, 11.57it/s]remote: waiting 3.0 seconds..
(P.S. - I can show you a screen log of my description above, where every time it slow works down to 1 it is fine, but once it gets to 0, it bounces back up to 31 secs again and again, over and over. If you want this screen capture, let me know, and I'll add it.)
receiving metadata:  11%|█████████▏                                                                             | 4553/43309 [05:32<52:39, 12.27it/s]remote: waiting 3.0 seconds..
receiving metadata:  11%|█████████▏                                                                             | 4603/43309 [05:36<50:51, 12.68it/s]remote: waiting 3.0 seconds..
receiving metadata:  11%|█████████▎                                                                             | 4653/43309 [05:39<49:53, 12.91it/s]remote: waiting 3.0 seconds..
receiving metadata:  11%|█████████▍                                                                             | 4703/43309 [05:43<48:24, 13.29it/s]remote: waiting 3.0 seconds..
receiving metadata:  11%|█████████▌                                                                             | 4753/43309 [05:46<47:19, 13.58it/s]remote: waiting 3.0 seconds..
remote: decreasing delay to 1
receiving metadata:  11%|█████████▋                                                                             | 4803/43309 [05:50<46:34, 13.78it/s]remote: waiting 1.0 seconds..
receiving metadata:  11%|█████████▋                                                                             | 4853/43309 [05:51<38:21, 16.71it/s]remote: waiting 1.0 seconds..
receiving metadata:  11%|█████████▊                                                                             | 4903/43309 [05:53<33:15, 19.24it/s]remote: waiting 1.0 seconds..
receiving metadata:  11%|█████████▉                                                                             | 4953/43309 [05:55<29:22, 21.76it/s]remote: waiting 1.0 seconds..
receiving metadata:  12%|██████████                                                                             | 5003/43309 [05:56<26:18, 24.27it/s]remote: waiting 1.0 seconds..
receiving metadata:  12%|██████████▏                                                                            | 5053/43309 [05:58<24:09, 26.39it/s]remote: waiting 1.0 seconds..
receiving metadata:  12%|██████████▎                                                                            | 5103/43309 [05:59<22:33, 28.22it/s]remote: waiting 1.0 seconds..
receiving metadata:  12%|██████████▎                                                                            | 5153/43309 [06:02<27:03, 23.50it/s]remote: waiting 1.0 seconds..
receiving metadata:  12%|██████████▍                                                                            | 5203/43309 [06:04<24:52, 25.54it/s]remote: waiting 1.0 seconds..
receiving metadata:  12%|██████████▌                                                                            | 5253/43309 [06:05<23:00, 27.57it/s]remote: waiting 1.0 seconds..
receiving metadata:  12%|██████████▋                                                                            | 5303/43309 [06:07<22:17, 28.41it/s]remote: waiting 1.0 seconds..
remote: decreasing delay to 0
receiving metadata:  19%|████████████████▍                                                                      | 8153/43309 [06:39<06:11, 94.66it/s]remote: user rate error, increasing delay to 1
remote: waiting 1.0 seconds..
receiving metadata:  19%|████████████████▍                                                                      | 8203/43309 [06:41<11:31, 50.74it/s]remote: waiting 1.0 seconds..
remote: user rate error, increasing delay to 3
remote: waiting 3.0 seconds..
remote: user rate error, increasing delay to 7
receiving metadata:  19%|████████████████▌                                                                      | 8253/43309 [06:46<24:46, 23.59it/s]remote: waiting 7.0 seconds..
remote: user rate error, increasing delay to 15
remote: waiting 15.0 seconds..
receiving metadata:  19%|████████████████                                                                    | 8255/43309 [07:09<34:00:52,  3.49s/it]remote: waiting 15.0 seconds..
receiving metadata:  19%|████████████████                                                                    | 8305/43309 [07:25<24:41:09,  2.54s/it]remote: waiting 15.0 seconds..
receiving metadata:  19%|████████████████▏                                                                   | 8355/43309 [07:41<18:10:06,  1.87s/it]remote: waiting 15.0 seconds..
receiving metadata:  19%|████████████████▎                                                                   | 8405/43309 [07:56<13:36:09,  1.40s/it]remote: waiting 15.0 seconds..
receiving metadata:  20%|████████████████▍                                                                   | 8455/43309 [08:12<10:24:44,  1.08s/it]remote: waiting 15.0 seconds..
receiving metadata:  20%|████████████████▋                                                                    | 8505/43309 [08:27<8:11:06,  1.18it/s]remote: waiting 15.0 seconds..
receiving metadata:  20%|████████████████▊                                                                    | 8555/43309 [08:43<6:37:34,  1.46it/s]remote: waiting 15.0 seconds..
receiving metadata:  20%|████████████████▉                                                                    | 8605/43309 [09:00<5:36:28,  1.72it/s]remote: waiting 15.0 seconds..
receiving metadata:  20%|████████████████▉                                                                    | 8655/43309 [09:15<4:49:05,  2.00it/s]remote: waiting 15.0 seconds..
receiving metadata:  20%|█████████████████                                                                    | 8705/43309 [09:31<4:15:46,  2.25it/s]remote: waiting 15.0 seconds..
remote: decreasing delay to 7
receiving metadata:  20%|█████████████████▏                                                                   | 8755/43309 [09:46<3:52:30,  2.48it/s]remote: waiting 7.0 seconds..
receiving metadata:  20%|█████████████████▎                                                                   | 8805/43309 [09:54<3:08:22,  3.05it/s]remote: waiting 7.0 seconds..
receiving metadata:  20%|█████████████████▍                                                                   | 8855/43309 [10:02<2:38:03,  3.63it/s]remote: waiting 7.0 seconds..
receiving metadata:  21%|█████████████████▍                                                                   | 8905/43309 [10:09<2:16:12,  4.21it/s]remote: waiting 7.0 seconds..
receiving metadata:  21%|█████████████████▌                                                                   | 8955/43309 [10:17<2:00:55,  4.73it/s]remote: waiting 7.0 seconds..
receiving metadata:  21%|█████████████████▋                                                                   | 9005/43309 [10:24<1:50:39,  5.17it/s]remote: waiting 7.0 seconds..
receiving metadata:  21%|█████████████████▊                                                                   | 9055/43309 [10:32<1:43:16,  5.53it/s]remote: waiting 7.0 seconds..
receiving metadata:  21%|█████████████████▊                                                                   | 9105/43309 [10:39<1:38:01,  5.82it/s]remote: waiting 7.0 seconds..
receiving metadata:  21%|█████████████████▉                                                                   | 9155/43309 [10:47<1:34:20,  6.03it/s]remote: waiting 7.0 seconds..
receiving metadata:  21%|██████████████████                                                                   | 9205/43309 [10:54<1:31:22,  6.22it/s]remote: waiting 7.0 seconds..
receiving metadata:  21%|██████████████████▏                                                                  | 9255/43309 [11:02<1:29:21,  6.35it/s]remote: waiting 7.0 seconds..
remote: decreasing delay to 3
receiving metadata:  21%|██████████████████▎                                                                  | 9305/43309 [11:09<1:28:07,  6.43it/s]remote: waiting 3.0 seconds..
receiving metadata:  22%|██████████████████▎                                                                  | 9355/43309 [11:13<1:14:06,  7.64it/s]remote: waiting 3.0 seconds..
receiving metadata:  22%|██████████████████▍                                                                  | 9405/43309 [11:17<1:03:50,  8.85it/s]remote: waiting 3.0 seconds..
receiving metadata:  22%|██████████████████▉                                                                    | 9455/43309 [11:20<57:16,  9.85it/s]remote: waiting 3.0 seconds..
receiving metadata:  22%|███████████████████                                                                    | 9505/43309 [11:24<52:10, 10.80it/s]remote: waiting 3.0 seconds..
receiving metadata:  22%|███████████████████▏                                                                   | 9555/43309 [11:27<48:29, 11.60it/s]remote: waiting 3.0 seconds..
receiving metadata:  22%|███████████████████▎                                                                   | 9605/43309 [11:31<45:38, 12.31it/s]remote: waiting 3.0 seconds..
receiving metadata:  22%|███████████████████▍                                                                   | 9655/43309 [11:34<43:47, 12.81it/s]remote: waiting 3.0 seconds..
receiving metadata:  22%|███████████████████▍                                                                   | 9705/43309 [11:40<47:39, 11.75it/s]remote: waiting 3.0 seconds..
receiving metadata:  23%|███████████████████▌                                                                   | 9755/43309 [11:43<45:24, 12.32it/s]remote: waiting 3.0 seconds..
receiving metadata:  23%|███████████████████▋                                                                   | 9805/43309 [11:47<43:30, 12.83it/s]remote: waiting 3.0 seconds..
remote: decreasing delay to 1
receiving metadata:  23%|███████████████████▊                                                                   | 9855/43309 [11:50<42:07, 13.24it/s]remote: waiting 1.0 seconds..
receiving metadata:  23%|███████████████████▉                                                                   | 9905/43309 [11:52<34:41, 16.05it/s]remote: waiting 1.0 seconds..
receiving metadata:  23%|███████████████████▉                                                                   | 9955/43309 [11:53<29:33, 18.81it/s]remote: waiting 1.0 seconds..
receiving metadata:  23%|███████████████████▊                                                                  | 10005/43309 [11:55<25:39, 21.63it/s]remote: waiting 1.0 seconds..
receiving metadata:  23%|███████████████████▉                                                                  | 10055/43309 [11:56<22:56, 24.16it/s]remote: waiting 1.0 seconds..
receiving metadata:  23%|████████████████████                                                                  | 10105/43309 [11:58<21:00, 26.35it/s]remote: waiting 1.0 seconds..
receiving metadata:  23%|████████████████████▏                                                                 | 10155/43309 [12:00<20:29, 26.97it/s]remote: waiting 1.0 seconds..
receiving metadata:  24%|████████████████████▎                                                                 | 10205/43309 [12:01<19:30, 28.29it/s]remote: waiting 1.0 seconds..
receiving metadata:  24%|████████████████████▎                                                                 | 10255/43309 [12:03<18:31, 29.75it/s]remote: waiting 1.0 seconds..
receiving metadata:  24%|████████████████████▍                                                                 | 10305/43309 [12:04<17:53, 30.75it/s]remote: waiting 1.0 seconds..
receiving metadata:  24%|████████████████████▌                                                                 | 10355/43309 [12:06<17:33, 31.29it/s]remote: waiting 1.0 seconds..
remote: decreasing delay to 0
receiving metadata:  30%|██████████████████████████                                                            | 13105/43309 [12:42<05:03, 99.38it/s]remote: user rate error, increasing delay to 1
receiving metadata:  30%|█████████████████████████▊                                                           | 13155/43309 [12:42<04:50, 103.90it/s]remote: waiting 1.0 seconds..
remote: user rate error, increasing delay to 3
remote: waiting 3.0 seconds..
remote: user rate error, increasing delay to 7
remote: waiting 7.0 seconds..
remote: user rate error, increasing delay to 15
remote: waiting 15.0 seconds..
receiving metadata:  30%|█████████████████████████▏                                                         | 13162/43309 [13:10<10:04:34,  1.20s/it]remote: waiting 15.0 seconds..
receiving metadata:  31%|█████████████████████████▋                                                          | 13212/43309 [13:26<7:49:18,  1.07it/s]remote: waiting 15.0 seconds..
receiving metadata:  31%|█████████████████████████▋                                                          | 13262/43309 [13:41<6:14:36,  1.34it/s]remote: waiting 15.0 seconds..
receiving metadata:  31%|█████████████████████████▊                                                          | 13312/43309 [13:57<5:08:53,  1.62it/s]remote: waiting 15.0 seconds..
receiving metadata:  31%|█████████████████████████▉                                                          | 13362/43309 [14:13<4:22:52,  1.90it/s]remote: waiting 15.0 seconds..
receiving metadata:  31%|██████████████████████████                                                          | 13412/43309 [14:28<3:50:23,  2.16it/s]remote: waiting 15.0 seconds..
receiving metadata:  31%|██████████████████████████                                                          | 13462/43309 [14:44<3:27:20,  2.40it/s]remote: waiting 15.0 seconds..
receiving metadata:  31%|██████████████████████████▏                                                         | 13512/43309 [14:59<3:11:27,  2.59it/s]remote: waiting 15.0 seconds..
receiving metadata:  31%|██████████████████████████▎                                                         | 13562/43309 [15:15<3:00:08,  2.75it/s]remote: waiting 15.0 seconds..
receiving metadata:  31%|██████████████████████████▍                                                         | 13612/43309 [15:30<2:52:05,  2.88it/s]remote: waiting 15.0 seconds..
remote: decreasing delay to 7
receiving metadata:  32%|██████████████████████████▍                                                         | 13662/43309 [15:47<2:50:42,  2.89it/s]remote: waiting 7.0 seconds..
receiving metadata:  32%|██████████████████████████▌                                                         | 13712/43309 [15:55<2:21:41,  3.48it/s]remote: waiting 7.0 seconds..
receiving metadata:  32%|██████████████████████████▋                                                         | 13762/43309 [16:03<2:01:41,  4.05it/s]remote: waiting 7.0 seconds..
receiving metadata:  32%|██████████████████████████▊                                                         | 13812/43309 [16:10<1:47:45,  4.56it/s]remote: waiting 7.0 seconds..
receiving metadata:  32%|██████████████████████████▉                                                         | 13862/43309 [16:18<1:38:45,  4.97it/s]remote: waiting 7.0 seconds..
receiving metadata:  32%|██████████████████████████▉                                                         | 13912/43309 [16:26<1:31:05,  5.38it/s]remote: waiting 7.0 seconds..
receiving metadata:  32%|███████████████████████████                                                         | 13962/43309 [16:33<1:25:43,  5.71it/s]remote: waiting 7.0 seconds..
receiving metadata:  32%|███████████████████████████▏                                                        | 14012/43309 [16:41<1:23:13,  5.87it/s]remote: waiting 7.0 seconds..
receiving metadata:  32%|███████████████████████████▎                                                        | 14062/43309 [16:49<1:20:42,  6.04it/s]remote: waiting 7.0 seconds..
receiving metadata:  33%|███████████████████████████▎                                                        | 14112/43309 [16:57<1:18:27,  6.20it/s]remote: waiting 7.0 seconds..
receiving metadata:  33%|███████████████████████████▍                                                        | 14162/43309 [17:04<1:17:05,  6.30it/s]remote: waiting 7.0 seconds..
remote: decreasing delay to 3
receiving metadata:  33%|███████████████████████████▌                                                        | 14212/43309 [17:12<1:16:00,  6.38it/s]remote: waiting 3.0 seconds..
receiving metadata:  33%|███████████████████████████▋                                                        | 14262/43309 [17:16<1:04:12,  7.54it/s]remote: waiting 3.0 seconds..
receiving metadata:  33%|████████████████████████████▍                                                         | 14312/43309 [17:20<57:16,  8.44it/s]remote: waiting 3.0 seconds..
receiving metadata:  33%|████████████████████████████▌                                                         | 14362/43309 [17:24<50:40,  9.52it/s]remote: waiting 3.0 seconds..
receiving metadata:  33%|████████████████████████████▌                                                         | 14412/43309 [17:27<46:32, 10.35it/s]remote: waiting 3.0 seconds..
receiving metadata:  33%|████████████████████████████▋                                                         | 14462/43309 [17:31<42:37, 11.28it/s]remote: waiting 3.0 seconds..
receiving metadata:  34%|████████████████████████████▊                                                         | 14512/43309 [17:34<39:49, 12.05it/s]remote: waiting 3.0 seconds..
receiving metadata:  34%|████████████████████████████▉                                                         | 14562/43309 [17:38<38:15, 12.52it/s]remote: waiting 3.0 seconds..
receiving metadata:  34%|█████████████████████████████                                                         | 14612/43309 [17:42<36:44, 13.02it/s]remote: waiting 3.0 seconds..
receiving metadata:  34%|█████████████████████████████                                                         | 14662/43309 [17:45<36:20, 13.14it/s]remote: waiting 3.0 seconds..
receiving metadata:  34%|█████████████████████████████▏                                                        | 14712/43309 [17:49<35:36, 13.38it/s]remote: waiting 3.0 seconds..
remote: decreasing delay to 1
receiving metadata:  34%|█████████████████████████████▎                                                        | 14762/43309 [17:52<34:42, 13.71it/s]remote: waiting 1.0 seconds..
receiving metadata:  34%|█████████████████████████████▍                                                        | 14812/43309 [17:54<29:20, 16.18it/s]remote: waiting 1.0 seconds..
receiving metadata:  34%|█████████████████████████████▌                                                        | 14862/43309 [17:56<24:47, 19.12it/s]remote: waiting 1.0 seconds..
receiving metadata:  34%|█████████████████████████████▌                                                        | 14912/43309 [17:57<21:37, 21.88it/s]remote: waiting 1.0 seconds..
receiving metadata:  35%|█████████████████████████████▋                                                        | 14962/43309 [17:59<19:24, 24.34it/s]remote: waiting 1.0 seconds..
receiving metadata:  35%|█████████████████████████████▊                                                        | 15012/43309 [18:00<18:14, 25.86it/s]remote: waiting 1.0 seconds..
receiving metadata:  35%|█████████████████████████████▉                                                        | 15062/43309 [18:02<16:54, 27.85it/s]remote: waiting 1.0 seconds..
receiving metadata:  35%|██████████████████████████████                                                        | 15112/43309 [18:03<16:00, 29.35it/s]remote: waiting 1.0 seconds..
receiving metadata:  35%|██████████████████████████████                                                        | 15162/43309 [18:05<15:31, 30.22it/s]remote: waiting 1.0 seconds..
receiving metadata:  35%|██████████████████████████████▏                                                       | 15212/43309 [18:06<15:07, 30.96it/s]remote: waiting 1.0 seconds..
receiving metadata:  35%|██████████████████████████████▎                                                       | 15262/43309 [18:08<16:01, 29.18it/s]remote: waiting 1.0 seconds..
remote: decreasing delay to 0
receiving metadata:  41%|███████████████████████████████████▍                                                  | 17862/43309 [18:45<12:04, 35.11it/s]remote: user rate error, increasing delay to 1
receiving metadata:  41%|███████████████████████████████████▌                                                  | 17912/43309 [18:46<09:32, 44.36it/s]remote: waiting 1.0 seconds..
remote: user rate error, increasing delay to 3
remote: waiting 3.0 seconds..
remote: user rate error, increasing delay to 7
remote: waiting 7.0 seconds..
remote: user rate error, increasing delay to 15
remote: waiting 15.0 seconds..
receiving metadata:  41%|██████████████████████████████████▎                                                | 17916/43309 [19:14<15:10:55,  2.15s/it]remote: waiting 15.0 seconds..
receiving metadata:  41%|██████████████████████████████████▍                                                | 17966/43309 [19:30<11:16:22,  1.60s/it]remote: waiting 15.0 seconds..
receiving metadata:  42%|██████████████████████████████████▉                                                 | 18016/43309 [19:46<8:31:54,  1.21s/it]remote: waiting 15.0 seconds..
receiving metadata:  42%|███████████████████████████████████                                                 | 18066/43309 [20:01<6:37:04,  1.06it/s]remote: waiting 15.0 seconds..
receiving metadata:  42%|███████████████████████████████████▏                                                | 18116/43309 [20:17<5:16:28,  1.33it/s]remote: waiting 15.0 seconds..
receiving metadata:  42%|███████████████████████████████████▏                                                | 18166/43309 [20:32<4:20:01,  1.61it/s]remote: waiting 15.0 seconds..
receiving metadata:  42%|███████████████████████████████████▎                                                | 18216/43309 [20:48<3:40:55,  1.89it/s]remote: waiting 15.0 seconds..
receiving metadata:  42%|███████████████████████████████████▍                                                | 18266/43309 [21:03<3:13:15,  2.16it/s]remote: waiting 15.0 seconds..
receiving metadata:  42%|███████████████████████████████████▌                                                | 18316/43309 [21:19<2:54:56,  2.38it/s]remote: waiting 15.0 seconds..
receiving metadata:  42%|███████████████████████████████████▌                                                | 18366/43309 [21:35<2:41:48,  2.57it/s]remote: waiting 15.0 seconds..

**Comment by gauteh** [comment]
Jeff Stern writes on July 9, 2020 1:39:
> Okay, thanks for the explanation. I'll just hang in there.
>
> Right now, every time I do a 'gmi sync' it takes an hour or two just to 'receive metadata' -- Even if I haven't sent anything new out. Rather frustrating..
>
> Why does it have to go through all 43,000 messages again, taking another hour or 2?

It will only do a full sync if it is too much out of date. Otherwise it does a
partial pull. After having done a successful `gmi sync` or e.g. `gmi pull -f`
you should have incremental and fast synchronizations afterwards (then it will
only fetch metadata of changed messages).

**Comment by gauteh** [comment]
It is increasing the delay from 1 second to more because the request failed (initially it does not have any delay). It will not help to force it to stay constant at 1, then it will just keep failing.
