### ISSUE TITLE
All the mails are marked as new in the first pull

### ISSUE THREAD

**Issue by Lattitude75** [gauteh/lieer#163]
I installed gmi on archlinux using the package on the AUR. My linux is 
```
Linux <uname> 5.7.6-arch1-1 #1 SMP PREEMPT Thu, 25 Jun 2020 00:14:47 +0000 x86_64 GNU/Linux
```
After the initial setup, I found that all the mails in the notmuch database were marked as new. Later, I also found that any email, even which is read on GMail online, if it does not exist in the local db is marked as new or unread. This is not expected as I want it to be synced properly with my online interface. 

Also, when I send a mail from gmail.com or using msmtp the sent mail is tagged in inbox too along with sent mail.

Can this be solved?

**Comment by Lattitude75** [comment]
Okay, I found the issue. In the notmuch config the section new shows the tags that should be added to any new mail. But, this is not necessary here as Gmail takes care of it in the first place. Including it in the local.py as self.new_tags is only making it difficult as it tags the emails unnecessarily. I am using it for now by just defining self.new_tags as an empty list. 

It is this following section in local.py:
```
    self.nmconfig = configparser.ConfigParser ()
    self.nmconfig.read (cfg)
    self.new_tags = self.nmconfig['new']['tags'].split (';')
    self.new_tags = [t.strip () for t in self.new_tags if len(t.strip()) > 0]
    self.new_tags=[] # new line which I added
``` 

This affects the function update_tags
```
  def update_tags (self, m, fname, db):
           .....
                  for t in self.new_tags:
                            nmsg.add_tag (t, True)
           .......
```
Thus, this particular new_tags functionality should be removed.

**Comment by Lattitude75** [comment]
Sorry, I got the answer from an old closed issue. I changed the notmuch-config for the issue.

**Comment by arjunkc** [comment]
Can you link to the issue you solved this from? I am having the same problem

**Comment by gauteh** [comment]
You need to remove new from new.tags in notmuch-config

søn. 26. jul. 2020, 06:53 skrev Arjun <notifications@github.com>:
