### ISSUE TITLE
Help with installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by idlethread** [gauteh/lieer#166]
_Originally posted by @gauteh in https://github.com/gauteh/lieer/issues/38#issuecomment-325793919_

> No, notmuch does not need to have anything to work on. It can use an 
> empty root, I don't have the chance to test this now, but for a fresh 
> install I think this should work (backup you mail!):
> 
> $ cd ~
> $ mkdir mail
> $ notmuch setup
> $ cd mail
> $ mkdir gmail.account1
> $ cd gmail.account1
> $ gmi init youraccount@gmail.com
> 

My root folder is `Mail` and my gmail account folder is `Personal`. I have done all this now and end up with a directory structure looking as follows. 

```
──• user@matterhorn •───(~) $ tree -a Mail/
Mail/
├── .notmuch
│   └── xapian
│       ├── flintlock
│       ├── iamglass
│       ├── postlist.glass
│       └── termlist.glass
└── Personal
    ├── .gmailieer.json
    └── mail
        ├── cur
        ├── new
        └── tmp

7 directories, 5 files

```

However, `gmi init` doesn't pop up any browser windows to request access to my gmail account. Instead I see the following error:

```
$ gmi init user@gmail.com
initializing repository in: /home/user/Mail/Personal..
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/lieer-1.2-py3.8.egg/lieer/local.py", line 279, in load_repository
  File "/home/user/.local/lib/python3.8/site-packages/notmuch/database.py", line 390, in get_directory
    raise FileError('Database().get_directory() called '
notmuch.errors.FileError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/bin/gmi", line 4, in <module>
    __import__('pkg_resources').run_script('lieer==1.2', 'gmi')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/home/user/.local/lib/python3.8/site-packages/lieer-1.2-py3.8.egg/EGG-INFO/scripts/gmi", line 24, in <module>
  File "/home/user/.local/lib/python3.8/site-packages/lieer-1.2-py3.8.egg/lieer/gmailieer.py", line 206, in main
  File "/home/user/.local/lib/python3.8/site-packages/lieer-1.2-py3.8.egg/lieer/gmailieer.py", line 213, in initialize
  File "/home/user/.local/lib/python3.8/site-packages/lieer-1.2-py3.8.egg/lieer/local.py", line 289, in load_repository
lieer.local.RepositoryException: local mail repository not in notmuch db
```

I've tried this several times after deleting .gmailieer.json and the mail folder to no avail.

What am I missing?

**Comment by gauteh** [comment]
That seems like it should work. What is your notmuch configuration? And what is your notmuch python version?

**Comment by idlethread** [comment]
@gauteh Thanks for your reply.
[
My `~/.notmuch-config` is as follows:

```
$ cat .notmuch-config | sed -e '/^[ \t]*#/d'

[database]
path=/home/user/Mail

[user]
name=Name Lastname
primary_email=user@gmail.com

[new]
tags=new;

ignore=/.*[.](json|lock|bak)$/

[maildir]
synchronize_flags=true

[search]
exclude_tags=
```
Various package version are as follows:

```
$ pip3 search notmuch
notmuch (0.29.2)             - Python binding of the notmuch mail search and indexing library.
  INSTALLED: 0.29.2 (latest)
afew (3.0.0)                 - An initial tagging script for notmuch mail
  INSTALLED: 3.0.0 (latest)
lieer (1.2)                  - Fast fetch and two-way tag synchronization between notmuch and GMail
  INSTALLED: 1.2 (latest)

$ apt policy libnotmuch5
libnotmuch5:
  Installed: 0.29.3-1ubuntu2

$ apt policy notmuch
notmuch:
  Installed: 0.29.3-1ubuntu2


```

**Comment by idlethread** [comment]
Nothing wrong in my configs?

**Comment by Lattitude75** [comment]
The notmuch database should be in the same directory where you are running the `gmi init` command. In this case, you should not make a new folder Personal in the directory where notmuch db is initiated. Follow the instructions in the Readme properly with the following command set.
```
mkdir mail
notmuch new
gmi init someone@something.com
```

**Comment by idlethread** [comment]
@Lattitude75 Thanks for your reply.

I followed @gauteh 's response here: https://github.com/gauteh/lieer/issues/38#issuecomment-325793919

I've tried the command you suggested from the Personal folder and it still gives the same error:

lieer.local.RepositoryException: local mail repository not in notmuch db

Step 1 in the README is a bit vague, in my opinion. What does `already setup with notmuch` mean in the case where I have no mail archives? What does it mean when I have existing mail synced through offlineimap or mbsync?

From the README:
```
This assumes your root mail folder is in ~/.mail and that this folder is already set up with notmuch.

Make a directory for the lieer storage and state files (local repository).
$ cd    ~/.mail
$ mkdir account.gmail
$ cd    account.gmail/
All commands should be run from the local mail repository unless otherwise specified.
```
What does `All commands should be run from the local mail repository` mean? `~/.mail `or `~/.mail/account.gmail`?

In the case of multiple mail accounts, there would still be only one .notmuch/xapian in the root folder (`~/Mail` in my case), right?
Where should I expect the `.gmailieer.json` and `mail` folder to be created?

I'd supply a patch to the README if I could only figure out how to get my setup working.

**Comment by Lattitude75** [comment]
Yes, all the commands in the case shows in README should be run from ~/.mail. 

From the README we have this command list:
```
Make a directory for the lieer storage and state files (local repository).
$ cd    ~/.mail
$ mkdir account.gmail
$ cd    account.gmail/
```
When I ran into errors, I found that the directory in which you are launching `gmi init` should have the directory .notmuch. That is, the notmuch database should be in that folder. I have the following set up for using Lieer with multiple accounts.

```
mail
├── mail1
│   ├── .credentials.gmailieer.json
│   ├── .gmailieer.json
│   ├── .gmailieer.json.bak
│   ├── .lock
│   ├── .notmuch
│   │   └── xapian
│   │       ├── docdata.glass
│   │       ├── flintlock
│   │       ├── iamglass
│   │       ├── position.glass
│   │       ├── postlist.glass
│   │       └── termlist.glass
│   ├── .notmuch.config
│   ├── .state.gmailieer.json
│   ├── .state.gmailieer.json.bak
│   ├── astroid_config
│   │   ├── astroid.config
│   │   └── poll.sh
│   └── mail
│       ├── cur [998 entries exceeds filelimit, not opening dir]
│       ├── new
│       └── tmp
├── mail2
│   ├── .credentials.gmailieer.json
│   ├── .gmailieer.json
│   ├── .gmailieer.json.bak
│   ├── .lock
│   ├── .notmuch
│   │   └── xapian
│   │       ├── docdata.glass
│   │       ├── flintlock
│   │       ├── iamglass
│   │       ├── position.glass
│   │       ├── postlist.glass
│   │       └── termlist.glass
│   ├── .notmuch.config
│   ├── .state.gmailieer.json
│   ├── .state.gmailieer.json.bak
│   ├── astroid_config
│   │   ├── astroid.config
│   │   ├── hooks
│   │   │   ├── delmail
│   │   │   ├── hook.log
│   │   │   └── undelmail
│   │   ├── keybindings
│   │   ├── keybindings.original
│   │   └── poll.sh
│   └── mail
│       ├── cur [199 entries exceeds filelimit, not opening dir]
│       ├── new
│       └── tmp
└── mail3
    ├── .credentials.gmailieer.json
    ├── .gmailieer.json
    ├── .gmailieer.json.bak
    ├── .lock
    ├── .notmuch
    │   └── xapian
    │       ├── docdata.glass
    │       ├── flintlock
    │       ├── iamglass
    │       ├── position.glass
    │       ├── postlist.glass
    │       └── termlist.glass
    ├── .notmuch.config
    ├── .state.gmailieer.json
    ├── .state.gmailieer.json.bak
    ├── astroid_config
    │   ├── astroid.config
    │   ├── hooks
    │   │   ├── delmail
    │   │   ├── hook.log
    │   │   └── undelmail
    │   ├── keybindings
    │   ├── keybindings.original
    │   └── poll.sh
    └── mail
        ├── cur [494 entries exceeds filelimit, not opening dir]
        ├── new
        └── tmp
```

Then I used the following script named astroid_script, with command `astroid_script <account>` where <account> is mail1 or mail2 or mail3.
```
#!/usr/bin/env bash

account=$1
# write the notmuch config environment to sublime_env.py file
echo "NOTMUCH_CONFIG='/home/saipavanchitta/mail/${account}/.notmuch.config'" > ~/.config/astroid/sublime_env.py

export NOTMUCH_CONFIG=~/mail/$account/.notmuch.config

astroid -c ~/mail/$account/astroid_config/astroid.config
```

I had to generate three separate notmuch db's for three emails. So, to add an email, for example email4, I follow this procedure:

```
$ cd ~/mail
$ mkdir mail4
```
Then I create a separate notmuch config file which in my case is .notmuch.config in the mail4 directory
```
$ export NOTMUCH_CONFIG=~/mail/mail4/.notmuch.config
$ notmuch new
$ git init someone@something.com
```

In the above tree, I also have seperate config files for Astriod which I use as my MUA. With the above, I do not have any errors as such.

**Comment by Lattitude75** [comment]
> In the case of multiple mail accounts, there would still be only one .notmuch/xapian in the root folder (`~/Mail` in my case), right?

That is what I tried to do, but it did not seem to work with Lieer. So, I created separate databases for each email I needed to sync.

**Comment by gauteh** [comment]
It is not necessary to have multiple databases.

fre. 24. jul. 2020, 09:44 skrev Lattitude75 <notifications@github.com>:

**Comment by gauteh** [comment]
Does your ~/.notmuch-config point to the correct path?

**Comment by gauteh** [comment]
We should print some more information on this error, like the notmuch database path etc. Also there has been issues if any of these are symlinks. Maybe you have to use the one it resolves to when configuring both notmuch and invoking gmi.

**Comment by idlethread** [comment]
> Does your ~/.notmuch-config point to the correct path?

It points to the root mail folder, `~/Mail` in my case.

`path=/home/user/Mail
`

**Comment by idlethread** [comment]
> We should print some more information on this error, like the notmuch database path etc. Also there has been issues if any of these are symlinks. Maybe you have to use the one it resolves to when configuring both notmuch and invoking gmi.

Bingo! That was it!

My `~/Mail` was a symlink. Changing the path in` ~/.notmuch-config` to point to the actual directory made it all work.

Thanks for the hint.
