### ISSUE TITLE
Sending mail with Lieer from Emacs fails: no 'gmi send' command

### ISSUE THREAD

**Issue by aapit** [gauteh/lieer#167]
First off, thank you for this wonderful project. 
Receiving mail from 2 Gmail boxes with Notmuch from Emacs works fabulous!

I'm now trying to get sending with Lieer to work.
I've configurated my Doom Emacs `init.el` (also tried in `config.el`) according to the [Lieer wiki](https://github.com/gauteh/lieer/wiki/GNU-Emacs-and-Lieer#sending-emails):
```emacs-lisp
(setq sendmail-program "gmi")
  (setq message-sendmail-extra-arguments '("send" "--quiet" "-t" "-C" "~/.mail/account.gmail"))
```
However, when I trigger `notmuch-mua-send`, this tries to call `gmi send`, to which Lieer replies:
_"gmi: error: argument action: invalid choice: 'send' (choose from 'pull', 'push', 'sync', 'auth', 'init', 'set')"_
Without above configuration, email does seem to get sent through the default sendmail interface, though I haven't configured that properly and have no use for it.

I'm probably missing something here. Do you know what that might be?

# Versions
- Lieer: `gmailieer 0.10-1` `apt` package from `focal/universe` 
  (is this version way behind and should I use the Git repo?
  I do prefer a package-managed version)
- Notmuch: `0.29.3`
- Emacs: `26.3`
- Doom Emacs: `2.0.9`
- Ubuntu: `20.04`

**Comment by gauteh** [comment]
Gmi is at 1.2 now 😊

**Comment by aapit** [comment]
Yep, that works, thank you! :sunglasses: 

I think newcomers could be helped by removing the long expired `apt` package, or mentioning that it's deprecated - since not everybody's entry point is the official Lieer site or the Github page. To illustrate: I stumbled on Lieer because someone mentioned `gmailieer` in a forum post somewhere, which is how I went down the `0-10` rabbit hole; lacking context.
I should obviously have read more closely, but no entry in `apt` is always better than an old version which doesn't mention it's an old version.

**Comment by gauteh** [comment]
That is up to Debian / Ubuntu. Better would be to upgrade the package. I am
not responsible for that package.

lør. 25. jul. 2020, 12:33 skrev David Spreekmeester <
notifications@github.com>:

**Comment by aapit** [comment]
Understandable! I wasn't sure how package management worked in terms of maintainer roles, in this case.
Unfortunately, it seems that there are already [2 upgrade requests for the Debian Lieer package](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=gmailieer;dist=unstable), the first one from December 2019.
So I don't think I can be of much help either, given the apparent bureaucracy layer over at Debian ;)

Anyway, keep up the good work! The world needs more awesome console based tools.

**Comment by gauteh** [comment]
👍 might help to bug them on the issue

søn. 26. jul. 2020, 12:03 skrev David Spreekmeester <
notifications@github.com>:

**Comment by aapit** [comment]
Will do! :fist_raised:
