### ISSUE TITLE
Sync an already synced and tagged maildir

### ISSUE THREAD

**Issue by arjunkc** [gauteh/lieer#170]
Hi 

I have an already synced and tagged maildir that I used to download with offlineimap. But offlineimap has given me a lot of trouble syncing even flagged messages recently. So I am in the process of switching to lieer. Since the messages are already tagged and such, I don't want to duplicate messages and tagging the same file.

Is there any way for lieer to handle this situation?

**Comment by gauteh** [comment]
No, not really. Lieer needs to know the gmail IDs, which are the stored in
the filename in a lieer sync. Maybe the message id can be enough to avoid
syncing the full file and only the metadata, but that is not supported.

søn. 26. jul. 2020, 05:30 skrev Arjun <notifications@github.com>:
