### ISSUE TITLE
Migrate to notmuch2

### ISSUE THREAD

**Issue by nackjicholson** [gauteh/lieer#173]
I saw this announcement https://notmuchmail.org/news/release-0.30/ in which they say they've officially deprecated the `notmuch` bindings in favor of `notmuch2`.

I'm interested what you think might be involved in migrating the bindings to notmuch2? It could be a good task for anyone looking to contribute to the project.

An aside:
Why isn't `notmuch` in the requirements.txt? I've had to install it with `pip install notmuch` to get lieer to run.

**Comment by gauteh** [comment]
Will Vaughn writes on August 1, 2020 20:34:
> I saw this announcement https://notmuchmail.org/news/release-0.30/ in which
> they say they've officially deprecated the `notmuch` bindings in favor of
> `notmuch2`.
>
> I'm interested what you think might be involved in migrating the bindings to
> notmuch2? It could be a good task for anyone looking to contribute to the
> project.

I don't think it is too difficult to do for a new contributor. I started at some
earlier point on a request from notmuch maintainers. But not all necessary
functionality had been implemented. It probably is now. The bindings were fairly
similar last time I checked.

>
> An aside:
> Why isn't `notmuch` in the requirements.txt? I've had to install it with `pip
> install notmuch` to get lieer to run.

It should be in the list.

**Comment by nackjicholson** [comment]
@gauteh I neglected to thank you for this awesome tool. Thank you! I've been using it for like 6 months, and I'm very happy with it. I learned about it from this Paul Ford [usesthis blog](https://usesthis.com/interviews/paul.ford/). Don't know if you're aware of it.

Also, I opened that #174 PR to add it to the reqs.

Best,
Will

**Comment by aplund** [comment]
It would seem this really need fixing as the next release of notmuch may not work anymore without using the new python bindings.  As per the release:

> Users are reminded that the old python bindings in bindings/python are deprecated; this will probably be the last major release that ships them.

**Comment by aplund** [comment]
I have tried to convert all calls from the notmuch interface to the notmuch2 interface and made a pull request: https://github.com/gauteh/lieer/pull/212

I might have missed some calls to the db, and I haven't done much more than very basic testing.

**Comment by gauteh** [comment]
Thanks!

On ubuntu 18 it seems that the notmuch version is not recent enough to use the notmuch2 bindings. It's not a deal-breaker, but it will prevent users from upgrading lieer for a while.

**Comment by barak** [comment]
I've merged the python3-notmuch2 branch into the Debian package and tried it. Am hoping to get it into Debian (and hence Ubuntu) soonish. Seemed to work okay until ...
```
$ gmi pull
pull: partial synchronization.. (hid: 30592866)
fetching changes: 100it [00:00, 191.10it/s]
fetching changes: 100it [00:00, 222.77it/s]
fetching changes: 100it [00:00, 248.05it/s]
...
fetching changes: 100it [00:00, 554.12it/s]
fetching changes: 100it [00:00, 546.97it/s]
fetching changes: 100it [00:04, 23.61it/s]
fetching changes: 96it [00:00, 102586.80it/s]                                                                                        | 0/4796 [00:00<?, ?it/s]
resolving changes: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 4796/4796 [00:00<00:00, 30868.72it/s]
receiving content:   0%|                                                                                                              | 0/729 [00:00<?, ?it/s]Traceback (most recent call last):                                                                                            | 1/729 [00:00<10:51,  1.12it/s]
  File "/usr/bin/gmi", line 24, in <module>
    g.main ()
  File "/usr/share/lieer/lieer/gmailieer.py", line 219, in main
    args.func (args)
  File "/usr/share/lieer/lieer/gmailieer.py", line 419, in pull
    self.partial_pull ()
  File "/usr/share/lieer/lieer/gmailieer.py", line 549, in partial_pull
    updated     = self.get_content (message_gids)
  File "/usr/share/lieer/lieer/gmailieer.py", line 755, in get_content
    self.remote.get_messages (need_content, _got_msgs, 'raw')
  File "/usr/share/lieer/lieer/remote.py", line 133, in func_wrap
    return func (self, *args, **kwargs)
  File "/usr/share/lieer/lieer/remote.py", line 384, in get_messages
    cb (msg_batch)
  File "/usr/share/lieer/lieer/gmailieer.py", line 753, in _got_msgs
    self.local.store (m, db)
  File "/usr/share/lieer/lieer/local.py", line 571, in store
    self.update_tags (m, p, db)
  File "/usr/share/lieer/lieer/local.py", line 641, in update_tags
    nmsg.tags |= labels
AttributeError: can't set attribute 'tags'
```

**Comment by gauteh** [comment]
Fixed in #212.

**Comment by barak** [comment]
Merged, tested, uploaded.

**Comment by gauteh** [comment]
Thanks!
