### ISSUE TITLE
Automatic Fetch of New Mail

### ISSUE THREAD

**Issue by mjmayer** [gauteh/lieer#180]
I am new to notmuch. Following the contents of the lieer README.md, I have managed to setup notmuch and have been able sync my mail with my gmail account using `gmi sync`.

I have added  'virtual-mailboxes' in neomutt and I can view emails in the notmuch database.

What is the recommended way to have lieer sync email on a regular basis? Should it just be crontab or is there hook of some sort I should be using in neomutt?

**Comment by gauteh** [comment]
Maybe the timout-hook is what you seek:
https://neomutt.org/feature/global-hooks

fre. 30. okt. 2020, 17:22 skrev Michael Mayer <notifications@github.com>:

**Comment by paulelms** [comment]
I also recommend imapnotify: https://wiki.archlinux.org/title/isync#with_imapnotify
