### ISSUE TITLE
yahoo mail support?

### ISSUE THREAD

**Issue by yeupou** [gauteh/lieer#181]
Hi,

Thanks for your work, I used it as described there https://yeupou.wordpress.com/2020/11/09/fetching-mails-from-gmail-com-with-lieer-notmuch-instead-of-fetchmail/ and it is convenient.
I however also have some decades old yahoo mail account I used to fetchmail from, and yahoo is following the example of google.
Any chance support for yahoo mail could be added without much fuss, or it is a completely different API?

**Comment by gauteh** [comment]
Hi, Yahoo probably using a completely different API if they have an API at all? Anyway, I think it is outside the scope of this tool unfortunately.
