### ISSUE TITLE
setup.py Error

### ISSUE THREAD

**Issue by ImranVirani** [gauteh/lieer#182]
When running ```python setup.py``` the error that follow is:

$ python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by gauteh** [comment]
You can get a list of commands for setup.py by doing python setup.py
--help-commands. But I think pip is recommended nowadays when installing
from the repo: pip install .

**Comment by ImranVirani** [comment]
Alright thank you
