### ISSUE TITLE
Local file exists crash

### ISSUE THREAD

**Issue by bobberb** [gauteh/lieer#184]
```
`pull: full synchronization (no previous synchronization state)

fetching messages: 20630it [00:22, 929.40it/s]               
                                                                      
removing deleted: 0it [00:00, ?it/s]

receiving content:   0%|                                              
                        
 | 1/20235 [00:01<6:58:59,  1.24s/it]

Traceback (most recent call last):

  File "/usr/bin/gmi", line 24, in <module>
    g.main ()

  File "/usr/lib/python3.9/site-packages/lieer/gmailieer.py", line 212, in main
    args.func (args)

  File "/usr/lib/python3.9/site-packages/lieer/gmailieer.py", line 411, in pull
    self.full_pull ()

  File "/usr/lib/python3.9/site-packages/lieer/gmailieer.py", line 656, in full_pull
    updated = self.get_content(message_gids)

  File "/usr/lib/python3.9/site-packages/lieer/gmailieer.py", line 751, in get_content
    self.remote.get_messages (need_content, _got_msgs, 'raw')

  File "/usr/lib/python3.9/site-packages/lieer/remote.py", line 133, in func_wrap
    return func (self, *args, **kwargs)

  File "/usr/lib/python3.9/site-packages/lieer/remote.py", line 384, in get_messages
    cb (msg_batch)

  File "/usr/lib/python3.9/site-packages/lieer/gmailieer.py", line 749, in _got_msgs
    self.local.store (m, db)

  File "/usr/lib/python3.9/site-packages/lieer/local.py", line 510, in store
    raise Local.RepositoryException ("local file already exists: %s" % p)

lieer.local.RepositoryException: local file already exists: /tank/jmail/.getmail/account.gmail/mail/cur/17618aa380c44b70:2,S
receiving content:   0%|                                                                       | 1/20235 [00:01<7:07:12,  1.27s/it]
`
```

Fresh install cannot proceed after crash during first run, now all subsequent runs stop at first message 1/20235.

**Comment by gauteh** [comment]
Do you have multiple instances of lieer running? Or symlinks involved in
your setup? Or any fs corruption?

søn. 13. des. 2020, 13:22 skrev bobberb <notifications@github.com>:

**Comment by bobberb** [comment]
@gauteh  there are no symlinks but .getmail is a gocryptfs mount.

**Comment by bobberb** [comment]
I moved the folders out of the gocryptfs, started gmi pull, sync begins but fails on the *same email* 
`cur/17618aa380c44b70:2,S
` which crashes the python process every time.

**Comment by gauteh** [comment]
Can you try to remove it from tmp/ ? Maybe lieer crashed and left it there. `gocryptfs` should work, I used to have everything in `encfs`.

**Comment by bobberb** [comment]
@gauteh Looks like something was stuck in tmp. Just to be safe I killed the whole account.gmail/mail folder and did a `mkdir -p mail/{cur,new,tmp}` before starting I new sync within the gocryptfs. Is now proceeding.

**Comment by gauteh** [comment]
Great. I am opted to not just try to recover from this error by overwriting the tmp file since there could be other programs syncing or using the file. Should be easier to figure out now that the error message is correct at least.
