### ISSUE TITLE
NameError in remote.py

### ISSUE THREAD

**Issue by j-hui** [gauteh/lieer#187]
I'm only just starting to use this, and I wasn't able to look closely into the issue, but there was a NameError thrown here: https://github.com/gauteh/lieer/blob/master/lieer/remote.py#L630

**Comment by gauteh** [comment]
Do you have any non-lieer files in your lieer maildir?

**Comment by j-hui** [comment]
I did at the time, I was still figuring out how to set things up (and have
since fixed that). But the NameError was a bug due to a variable not being
defined.

**Comment by gauteh** [comment]
Ah right, I'll check. Maybe an error in the error message.

tor. 18. feb. 2021, 17:43 skrev John Hui <notifications@github.com>:

> I did at the time, I was still figuring out how to set things up (and have
> since fixed that). But the NameError was a bug due to a variable not being
> defined.
>
