### ISSUE TITLE
Sending mail from Emacs notmuch with multiple accounts

### ISSUE THREAD

**Issue by j-hui** [gauteh/lieer#188]
Forgive me if I'm missing something, but how should one configure Emacs notmuch to support multiple mailboxes?

The Wiki instructs me to add this to our init file:

```
    (setq sendmail-program "gmi")
    (setq message-sendmail-extra-arguments '("send" "--quiet" "-t" "-C" "~/.mail/account.gmail"))
```

However, this only allows me to send from the account credentials under `account.gmail`. Is there a way to send mail using a different Gmail account?

**Comment by sten0** [comment]
+1, I've also encountered this limitation.   Using `message-sendmail-envelope-from`, and a variety of other methods, I was also unable to make it work.  I have confirmed multiple-account support functions correctly when using `msmtp` or `postfix`.

@gauteh, do you know if this is a limitation of the Gmail API?  If not, would you please consider enabling richer `sendmail -f` support.

@j-hui, here's a hint for something undocumented but that makes total sense once you know about it:  In ~/.notmuch-config, make sure you set `other_email` to the address, or list of addresses that you need to use.

**Comment by sten0** [comment]
P.S. @j-hui, sorry for the incomplete solution.  You'll need
```
      mail-specify-envelope-from t
      message-sendmail-envelope-from 'header
      mail-envelope-from 'header
      notmuch-always-prompt-for-sender t ;; optional
```

to replicate my success with msmtp or Postfix...which sadly I've been unable to replicate today.  It appears that Gmail might no longer support this :-/  Gmail appears to now move the `From:` header that uses `other_email` to `X-Google-Original-From:`, and it then appears to rewrite `From:` to use primary foo@gmail.com account :-(

**Comment by gauteh** [comment]
Do you use envelope-from to determine which account? What other sendmail
programs support that, and how?

tor. 25. feb. 2021, 22:05 skrev Nicholas D Steeves <notifications@github.com

**Comment by gregoryhugaerts** [comment]
took some reading through help buffers, but this seems to work:
```
(add-hook 'message-send-hook (lambda ()
				 (let (from (message-fetch-field "from"))
				   (if (string= from "$FULL_FROM_MAIL")
				       (setq message-sendmail-extra-arguments '("send" "--quiet" "-t" "-C" "$FIRST_MAIL_DIR"))
				     (setq message-sendmail-extra-arguments '("send" "--quiet" "-t" "-C" "$SECOND_MAIL_DIR"))))))
```

**Comment by sten0** [comment]
@gauteh, would you please reopen this issue?  Sorry for the delay, it seems my reply was lost in my drafts folder (I am frequently without internet).  Here are some links to the common methods I'm aware of:
https://sqrtminusone.xyz/posts/2021-02-27-gmail/
https://www.reddit.com/r/emacs/comments/9piml5/a_few_quick_emacsnotmuch_questions/
https://emacs.stackexchange.com/questions/63521/fetching-email-from-multiple-accounts-via-both-lieer-gmailieer-and-isync-with

I actually use Postfix to choose a SMTP smart host (forwarder), and msmtp-mta on my laptop.  The two cases I'd like to see Lieer-provided documentation for are:
1. Multiple GMail accounts using Lieer's sendmail transport
2. Mixing one or more GMail accounts with a non-Google account--this is also a common case, and many people do not want to (or are not allowed to) forward their non-GMail email to Google.
 
@gregoryhugaerts thank you for your solution!  Are you interested in working on and submitting a PR?

**Comment by gauteh** [comment]
I think this documentation should go in the wiki under the emacs part. Please edit it directly (should be open for anyone).

**Comment by gregoryhugaerts** [comment]
Added it to wiki

**Comment by gauteh** [comment]
Thanks
