### ISSUE TITLE
Use "deleted" tag?

### ISSUE THREAD

**Issue by mkleehammer** [gauteh/lieer#189]
Would it be possible to change the local tag "trash" to "deleted" instead to match the notmuch Emacs UI?  If I understand correctly, the notmuch DB doesn't care but the Emacs lisp code uses "deleted" in a few places.  My current test will be overriding it with "trash" everywhere, but it seems like it would be easier to map in Lieer.

I tried changing the local map from "trash" to "deleted" in local.py, but I kept getting the error about pushing an invalid tag.  It seems like it was somehow trying to push "trash" still.  I didn't see any remote mapping so I assumed it uses the same mapping.

If it is easy enough, it seems like it would be a nice configuration option.  Thoughts?

**Comment by gauteh** [comment]
Did you try to change it in local.py:37? If you still have messages tagged with trash locally it will try to push them with that label, you would have to change all tags to deleted in that case. Note that stuff that is labeled TRASH is eventually deleted.

**Comment by mkleehammer** [comment]
Hmmm...  That is where I changed it and when I just tried to reproduce it, I could not.  The "deleted" tag was successfully translated to "trash".  It's possible I accidentally also had a "trash" tag set in my previous test.

Now that we know it works, what are your thoughts on having the trash tag be a configuration setting?

**Comment by gauteh** [comment]
Fixed in #190 .
