### ISSUE TITLE
Lock up using gmi in notmuch-hooks

### ISSUE THREAD

**Issue by stdbull** [gauteh/lieer#195]
Hi @gauteh 
As I mentioned in #67 I've set up a new machine and moved my mailstore.
Everything is working fine - both with notmuch and gmi.

I have these versions:
<pre>
notmuch 0.31.4+137~g6967dcb
gmi  v1.3+4~e866271
</pre>

I wanted to switch my mail syncing to so that gmi was invoked from the notmuch-hooks (5).
https://notmuchmail.org/manpages/notmuch-hooks-5/

Specifically, I call gmi pull from pre-new and gmi push from post-new.
What I observe is that if I invoke gmi pull -C /home/myhome/path/to/maildir/gmaildir/ from within the Notmuch $DATABASEDIR/.notmuch/hooks/pre-new hook, gmi fetches mail, but then locks up because it seems to not be able to open the DB.

Here is a back trace after ctrl-c:

```
[~]
$ notmuch new
path: /home/myhome/path/to/maildir/gmaildir/
pull: partial synchronization.. (hid: 66446860)
fetching changes ....fetching changes ....fetching changes ....fetching changes ...resolving changes (376) ........................................receiving content (156) ...^C
Traceback (most recent call last):
  File "/home/myhome/git/lieer/gmi", line 24, in <module>
    g.main ()
  File "/home/myhome/git/lieer/lieer/gmailieer.py", line 215, in main
    args.func (args)
  File "/home/myhome/git/lieer/lieer/gmailieer.py", line 418, in pull
    self.partial_pull ()
  File "/home/myhome/git/lieer/lieer/gmailieer.py", line 548, in partial_pull
    updated     = self.get_content (message_gids)
  File "/home/myhome/git/lieer/lieer/gmailieer.py", line 754, in get_content
    self.remote.get_messages (need_content, _got_msgs, 'raw')
  File "/home/myhome/git/lieer/lieer/remote.py", line 133, in func_wrap
    return func (self, *args, **kwargs)
  File "/home/myhome/git/lieer/lieer/remote.py", line 384, in get_messages
    cb (msg_batch)
  File "/home/myhome/git/lieer/lieer/gmailieer.py", line 749, in _got_msgs
    with notmuch.Database (mode = notmuch.Database.MODE.READ_WRITE) as db:
  File "/usr/local/lib/python3.8/dist-packages/notmuch/database.py", line 164, in __init__
    self.open(path, mode)
  File "/usr/local/lib/python3.8/dist-packages/notmuch/database.py", line 223, in open
    status = Database._open(_str(path), mode, byref(db))
KeyboardInterrupt

```

I've seen some posts from others using this successfully, but they are from a couple of years ago.
I am wondering if something has changed in notmuch or lieer which could explain this.
Any thoughts?

Here is some more env info:

<pre>
[~/git/lieer]
(master)$ git rev-parse HEAD
e866271dd092e9e1f5a1ef59c928ca48bcf1456c

[~/git/lieer]
(master)$ git st
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean

[~/git/lieer]
(master)$ cat ~/path/to/maildir/.notmuch/hooks/pre-new          
#!/usr/bin/env bash
/home/myhome/git/lieer/gmi pull -C ~/path/to/maildir/gmaildir/
</pre>

I can obviously work around it, but it would be nice to understand what has happened such that gmi is not able to be used in the pre-new hook (I've not tried post-new).

The docs for notmuch-hooks (5) say:
<pre>
       pre-new
              This hook is invoked by  the  new  command  before  scanning  or
              importing  new  messages  into  the database. If this hook exits
              with a non-zero status, notmuch will abort further processing of
              the new command.

              Typically  this hook is used for fetching or delivering new mail
              to be imported into the database.

       post-new
              This hook is invoked by the new command after new messages  have
              been  imported  into  the  database  and  initial tags have been
              applied. The hook will not be run if there have been any  errors
              during the scan or import.

              Typically  this  hook  is used to perform additional query-based
              tagging on the imported messages.
</pre>
The wording for both of these suggest that the dastabase is not locked when these hooks are run.

What do you think?

Cheers,
Matt

**Comment by gauteh** [comment]
Could there be any other program (including notmuch CLI itself) that has
the database open in read-only or write-mode at the time? What happens if
you try to tag a message using notmuch cli while gmi is hanging? From the
docs it does not seem like notmuch should have an open db instance (in RW
mode) yet, but this might still be the case?

**Comment by gauteh** [comment]
Note that you do not need to run notmuch new after gmi pull, the db is
already updated by gmi. I understand that there might be other use-cases
that makes this useful though.

**Comment by stdbull** [comment]
There's no other program open (including notmuch CLI itself) when gmi hangs. I note that there are two processes seen by ps aux | grep notmuch but I guess that's expected when executing the hook.

Also, when gmi hangs, I can't tag an email - the notmuch tag command hangs.
As suspected, it's because it's trying to grab (open) the DB:
<pre>
stat("/home/myhome/path/to/maildir//.notmuch", {st_mode=S_IFDIR|0755, st_size=22, ...}) = 0
stat("/home/myhome/path/to/maildir//.notmuch/xapian", {st_mode=S_IFDIR|0755, st_size=144, ...}) = 0
stat("/home/myhome/path/to/maildir//.notmuch/xapian/iamchert", 0x7ffc2f62de50) = -1 ENOENT (No such file or directory)
stat("/home/myhome/path/to/maildir//.notmuch/xapian/iamglass", {st_mode=S_IFREG|0664, st_size=154, ...}) = 0
stat("/home/myhome/path/to/maildir//.notmuch/xapian/postlist.glass", {st_mode=S_IFREG|0664, st_size=1395146752, ...}) = 0
openat(AT_FDCWD, "/home/myhome/path/to/maildir//.notmuch/xapian/flintlock", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
fcntl(3, F_OFD_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=1}
</pre>

When gmi hangs, the same lock is being attempted.
If I strace notmuch new, the lock is opened by notmuch...

<pre>
..
openat(AT_FDCWD, "/home/myhome/path/to/maildir//.notmuch/xapian/flintlock", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 3
fcntl(3, F_OFD_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=1}) = 0
openat(AT_FDCWD, "/home/ml943601/b/mail/brcm//.notmuch/xapian/iamglass", O_RDONLY) = 4
..
</pre>
...but fd 3 is never closed before the hook is executed.
I guess this is the problem..

Cheers,
Matt

**Comment by gauteh** [comment]
Ok, could that be a notmuch-bug? Why would notmuch require the db to be
open when calling the hook?

**Comment by stdbull** [comment]
DB agrees it's a bug and he'll fix it. We can probably close this :-)
