### ISSUE TITLE
Sync renamed label/tag

### ISSUE THREAD

**Issue by ntrocado** [gauteh/lieer#199]
I renamed a label on gmail, but my local tag still exhibits the old name after syncing. How can I update this?

**Comment by gauteh** [comment]
You can always do a full pull, but that takes a long time. Alternatively
change it again online to trigger it. Are you sure the tag is not in your
ignored list?

**Comment by ntrocado** [comment]
I started a full pull, aborted it because it was taking a long time, but got the new tag to appear along with the old one. Then I manually tagged the relevant messages, synced, and all is fine now. I don't know what the problem was though... Anyway, thanks!
