### ISSUE TITLE
Atomically update the state file

### ISSUE THREAD

**Issue by wiktor-k** [gauteh/lieer#200]
Hi,

I just had a system crash during lieer update and apparently the `.state.gmailieer.json` file was empty afterwards. I don't want to reproduce it :) but I was wondering if lieer is using [atomic updates](https://stackoverflow.com/a/18706666) to always keep the file consistent? (e.g. creating new file with new state and then `mv`ing the new file to the old name).

I hope this issue is not a fluke but it may be so if something's wrong please close it and sorry for the noise! :)

**Comment by gauteh** [comment]
Hi, we're already doing that: https://github.com/gauteh/lieer/blob/master/lieer/local.py#L284, there should be a backup file: https://github.com/gauteh/lieer/blob/master/lieer/local.py#L282, maybe it can be useful?

**Comment by wiktor-k** [comment]
Yep, great! The `bak` file was in there... not sure why the original file was truncated.

Either way this looks legit so I'm closing. Thank you for your time! :+1:

**Comment by mikwielgus** [comment]
I have this problem with Lieer 1.3. I use a cron job that runs Lieer every one minute, and every some time Lieer stops working because `.state.gmailieer.json` is empty. Overriding it with the backup file helps, but I would prefer not having to do this.

**Comment by gauteh** [comment]
Hi,

I think there might be a race in order of locking repo and loading state
file. Please see if #202 works. If not, also make sure you are not running
out of disk-space.

-- gaute

**Comment by mikwielgus** [comment]
Really sorry for the long delay before reply.

Just now I've installed the newest version of the `master` branch, to which you committed #202 today. I'll let you know if the reported problem persists.
