### ISSUE TITLE
confused about unread tag

### ISSUE THREAD

**Issue by aaptel** [gauteh/lieer#201]
Hi

My notmuch config has:

```
[new]
ignore=/.*[.](json|lock|bak)$/
tags=unread;inbox
```

My lieer config has:

```
{"replace_slash_with_dot": false, "account": "-----@gmail.com", "timeout": 600, "drop_non_existing_label": false, "ignore_empty_history": false, "ignore_tags": [], "ignore_remote_labels": ["CATEGORY_SOCIAL", "CATEGORY_UPDATES", "CATEGORY_PROMOTIONS", "CATEGORY_PERSONAL", "CATEGORY_FORUMS"], "remove_local_messages": true, "file_extension": "", "local_trash_tag": "trash", "translation_list_overlay": []}

```

I believe these are the default for both.

I've done the initial 11GB pull (!) but all the emails have the unread tag in notmuch. It doesnt look like gmail remote unread tag is synced with the local maildir unread tag :(

I'm not sure if this is a bug or if I'm confused about the settings...

Thanks!

**Comment by gauteh** [comment]
All tags listed in `new.tags` will be added on pull by gmi, you'd want
clear that list or maybe add `new` - and then immediately clear it as part
of post-sync processing to avoid it being pushed back up. There are also
ways to ignore tags, but that is not what you want here. I think the best
way out of this is to:

1) Clear the list in `new.tags` in .notmuch-config,
2) then do a `gmi pull -f` to reset the local tags (won't pull the
message-files anew).

**Comment by aaptel** [comment]
that seemed to work thanks!
