### ISSUE TITLE
Caught in "historyId is too old" loop

### ISSUE THREAD

**Issue by mjg** [gauteh/lieer#203]
With an unchanged lieeer 1.3 I suddenly ended up in a "historyId is too old" loop a few days ago:
```
push: everything is up-to-date.
pull: partial synchronization.. (hid: 47913)
pull: historyId is too old, full sync required.
fetching messages: 100%|█████████████████████████████████████████| 39/39 [00:00<00:00, 48.09it/s]
removing deleted: 0it [00:00, ?it/s]
receiving content: everything up-to-date.
receiving metadata: 100%|███████████████████████████████████████| 39/39 [00:00<00:00, 109.93it/s]
pull: complete, removing resume file
current historyId: 47913, current revision: 670957
```
And the next run gives exactly the same message with the same numbers, and they agree with both the state file and its backup.

The very first time that this happened the numbers switched from 49017/638749 to the ones above, as if GMails history IDs went backwards - or maybe one of the API-pages gives a 404 for reasons different from lieer's expectations?

[The same happens on another much larger GMail account where I don't want to try the full fetch just yet...]

**Comment by mjg** [comment]
And sure enough, after a few days, and after forcing a mailbox change, but few minutes after posting this issue, things went back to normal. Still stomped, but maybe at some point the GMail api does answer "since x" when x is too old.

**Comment by gauteh** [comment]
Good 😊

lør. 11. sep. 2021, 17:30 skrev Michael J Gruber ***@***.***>:
