### ISSUE TITLE
Sync and send suddenly slow

### ISSUE THREAD

**Issue by onecan** [gauteh/lieer#206]
First off, thank you for writing this great tool! I've been using it for almost a year; I am generally very pleased with it.

The the last few days, gmi sync has begun to take 2-3 minutes to finish and gmi send does not seem to ever finish.
Is some change to Gmail causing this?

I've tried switching to a personal API key in case the one packaged with lieer was being throttled, but to no avail.

Thanks for your help!

**Comment by gauteh** [comment]
Sometimes gmail api throttles you if you have made a lot of requests, has this resolved itself?
