### ISSUE TITLE
Label name exists or conflicts - case issue?

### ISSUE THREAD

**Issue by isakrubin** [gauteh/lieer#207]
Is there a solution to the "Label name exists or conflicts" problem when changing a label to lowercase on gmail while the local tag still is uppercase?

In my case I had a tag "Amazon" which synced fine, I then changed the label on gmail to lowercase "amazon", and while syncing it complains about "Label name exists or conflicts" .

push: creating label: Amazon..
...
/labels?alt=json returned "Label name exists or conflicts". Details: "[{'message': 'Label name exists or conflicts', 'domain': 'global', 'reason': 'aborted'}..

**Comment by gauteh** [comment]
I don't think we have a solution for that. Except that you maybe have to create an intermediate tag, delete the `Amazon` tag using the gmail interface, then create a new `amazon label`. Or maybe you can change it in the gmail interface?
