### ISSUE TITLE
gmi sync didn't work

### ISSUE THREAD

**Issue by bkkavin** [gauteh/lieer#220]
https://sqrtminusone.xyz/posts/2021-02-27-gmail/

I followed the instructions in above blog. I created an app password. 
When I ran gmi init mail@gmail.com browser opened and it showed all my google accounts. I selected the correct email. It asks for permissions. I pressed allow. It just shows " Something went wrong there. Try again". 
What should I do. Is there any other way to do this?

**Comment by gauteh** [comment]
Still an issue?

**Comment by skangas** [comment]
Duplicate of #215?
