### ISSUE TITLE
Sync "receiving content" slow; 20-60 seconds per it

### ISSUE THREAD

**Issue by cashpw** [gauteh/lieer#222]
```
$ gmi sync
...
fetching changes: 100it [00:02, 36.67it/s]
fetching changes: 100it [00:02, 33.98it/s]
fetching changes: 100it [00:02, 36.36it/s]
fetching changes: 100it [00:02, 45.15it/s]
fetching changes: 100it [00:02, 45.46it/s]
fetching changes: 100it [00:01, 50.05it/s]
fetching changes: 100it [00:01, 66.90it/s]
fetching changes: 100it [00:01, 76.24it/s]
fetching changes: 100it [00:01, 98.92it/s]
fetching changes: 100it [00:00, 151.48it/s]
fetching changes: 100it [00:00, 147.97it/s]
resolving changes: 100%|███████████████████| 72597/72597 [04:33<00:00, 265.57it/s]
receiving content:  14%|███████████████▊            | 515/3864 [5:54:33<51:37:44, 55.50s/it]
```

I'm filing this bug to seek comments and to give me a place to document this in case anything I do can help someone in the future.

I've used `lieer` for a 1+ years now and have never seen `sync` take so long until now. I've been at the "receiving content" stage for a three days now. I've restarted the process occasionally and have seen similar speed (e.g. `20-60s/it`) consistently. I don't see any indication of throttling -- the speed starts off slow and remains slow.

Has there been anything in the past which has caused such slow `sync`-ing?

**Comment by gauteh** [comment]
Maybe you were throttled for some reason. Still an issue?
