### ISSUE TITLE
gmi init/auth failure

### ISSUE THREAD

**Issue by nullomata** [gauteh/lieer#228]
After installing lieer, I navigate into my gmail directory `~/.mail/gmail/` and use `gmi init <my_account>@gmail.com` which takes me to the google sign-on/authentication screen. When I select my account and then grant access, google returns "Something went wrong... Sorry, something went wrong there. Try again." with the only option being to click next. But this takes me to my account page and gives no guidance on how to resolve the error. 

I created a project in the developer console, created an API key, and set myself up as the owner and then created a OAuth authorization key for my test users, included my email as a test user, and then ran `gmi init -c my_client_secret.json <my_account>@gmail.com` which opened a webpage stating that "Google hasn't verified this app..." with an option to either continue or go back to safety. After clicking continue, I again get "Something went wrong..." which leads me back to my account page. 

I followed the guide from https://github.com/gauteh/lieer/issues/137 but that doesn't seem to be working. Any suggestions on what is going wrong?

**Comment by gauteh** [comment]
Maybe it is related to https://github.com/gauteh/lieer/issues/215. However, it seems to have been working recently: e.g. https://github.com/gauteh/lieer/pull/223 .

**Comment by gauteh** [comment]
Also make sure that you use the original account name you signed up with: https://github.com/gauteh/lieer#caveats

**Comment by danielclucas** [comment]
Thanks for the links and suggestion. I tried both <account>@gmail.com and <account>@googlemail.com but neither work. 

To be clear, `gmi init` isn't working for me with either the default API key that lieer uses, nor with my own API key. I've tried both options and I get the same "Something went wrong" error.

**Comment by skangas** [comment]
> However, it seems to have been working recently: e.g. #223 .

According to [Google](https://developers.google.com/identity/protocols/oauth2/resources/oob-migration#key-compliance-dates), here's the timeline:

> February 28, 2022 - new OAuth usage blocked for the OOB flow
> September 5, 2022 - a user-facing warning message may be displayed to non-compliant OAuth requests
> October 3, 2022 - the OOB flow is deprecated for OAuth clients created before February 28, 2022 
>  January 31, 2023 - all existing clients are blocked (including exempted clients). Clients may request a one-time extension to continue using the OOB flow until January 31, 2023, as instructed in the email message sent to affected clients. 

So I guess after January 31, 2023, this will stop working for everyone?

**Comment by skangas** [comment]
Could you please try again now that https://github.com/gauteh/lieer/commit/a4ab209c721de7146f4301b426bdb6482d687a85 has been merged?

**Comment by rdbeni0** [comment]
> Could you please try again now that [a4ab209](https://github.com/gauteh/lieer/commit/a4ab209c721de7146f4301b426bdb6482d687a85) has been merged?

hi, i am new lieer/gmi user, but its not working (just tried).
received: "Something went wrong
Sorry, something went wrong there. Please try again."
so cannot use it

**Comment by danielclucas** [comment]
@skangas unfortunately I am still getting the same error as described above.

**Comment by isakrubin** [comment]
seems to still be an issue
