### ISSUE TITLE
Replace deprecated and unmaintained oauth2client library

### ISSUE THREAD

**Issue by skangas** [gauteh/lieer#230]
The oauth2client has been deprecated for a long time. It was [last released](https://pypi.org/project/oauth2client/) on Sep 7, 2018, and its GitHub [repository](https://github.com/googleapis/oauth2client) was archived on Nov 9, 2022. It should be replaced with some alternative.

According to the [oauth2client](https://pypi.org/project/oauth2client/) page on pypi:
> Note: oauth2client is now deprecated. No more features will be added to the libraries and the core team is turning down support. We recommend you use [google-auth](https://google-auth.readthedocs.io/) and [oauthlib](http://oauthlib.readthedocs.io/).

**Comment by granquet** [comment]
I've created this PR to fix this issue: https://github.com/gauteh/lieer/pull/242

**Comment by skangas** [comment]
> I've created this PR to fix this issue: #242

Thanks.

If you include the text `(fix #242)` somewhere in your commit message, this ticket should be closed automatically when your PR is merged.
