### ISSUE TITLE
Unable to complete or limited initial pull

### ISSUE THREAD

**Issue by algal** [gauteh/lieer#233]
I'm unable to complete the initial pull. Whenever I try `gmi pull` or `gmi pull --resume`, it ends with `socket.timeout: The read operation timed out` or else `TimeOutError: [Errno 60] Operation timed out`.

As a workaround, I tried pulling only a smaller number of messages, but a command like `gmi pull --resume --limit 100` leads to a different error: `ValueError: --limit with "remove_local_messages" will cause lots of messages to be deleted`

Are these errors expected for large accounts or for the stable v1.3 build?

I've authenticated successfully. I'm running version 1.3, installed via pip inside a condo environment running Python 3.6.9, on macOS 12.6.2.

**Comment by gauteh** [comment]
Maybe related to oauth flow. Should work with large accounts, check benchmarks in wiki.
