### ISSUE TITLE
code style guidelines

### ISSUE THREAD

**Issue by digitalsignalperson** [gauteh/lieer#244]
Any thoughts on setting some style guidelines for this project and doing a pass of the repo through a code formatter?

I noticed a mix of spaces between method and parenthesis or not, which made it hard to search for e.g. all uses of the `users()` api:

- without space `users()` 
`return self.service.users().messages().send(userId = self.account, body = message).execute()`

- with space `users ()` 
`self.service.users ().labels ().list (userId = self.account).execute ()`

Also there are some files with 4 space indentation, some with 2.

I'm biased to PEP8 and the familiarity of that, and totally not logical of me but I felt a little uneasy first looking at the codebase (brain goes "oh, how do I trust this code, it has 2 space indentation!!"). Also not intending this as criticism, I'm liking using this code and the project!

**Comment by gauteh** [comment]
Totally agree. Since this project I always use yapf or similar to format the code, then it is automatic and no need for manual maintaining or discussion.

**Comment by digitalsignalperson** [comment]
black could be a easy no config no decisions option too
and even be hooked in to a github action https://github.com/marketplace/actions/run-black-formatter

**Comment by gauteh** [comment]
Happy to review a PR changing the style and adding CI.

**Comment by digitalsignalperson** [comment]
added https://github.com/gauteh/lieer/pull/247
