### ISSUE TITLE
Google API polling frequency recommendation

### ISSUE THREAD

**Issue by skangas** [gauteh/lieer#255]
I'm currently running `gmi sync` automatically every 5 minutes, but I don't know if it is allowed to poll the Google API that often. I tried to look for documentation here, and searching the Google documentation, but I came up short. Perhaps my search-fu is too weak. So:

- Do we know anything about this?
- If yes, should best practices perhaps be documented under "Caveats" in `README.md`?

Thanks!

**Comment by gauteh** [comment]
You should be able to poll often, gmi only checks historyid. I usually have it at one minute.
