### ISSUE TITLE
Re-authentication in 1.5, and it needs a GUI

### ISSUE THREAD

**Issue by barak** [gauteh/lieer#257]
Using v1.4, `gmi pull` gets all my new gmail. Great!

Using v1.5, `gmi pull` tries to pop up a web page for me to authenticate. (Which doesn't work because I'm using SSH to a shell, so it gets a non-graphical browser which can't handle this stuff; and when I quit that it freezes.) Can't it re-use my old credentials? Or at least, explain how to do it by editing files or inputting those Google per-app passwords and such.

(I'm the Debian packager for this, BTW.)

**Comment by gauteh** [comment]
Yes, sorry about that. Gmi basically didn't work for new users, and I didn't have more resources to deal with a smoother migration.

**Comment by barak** [comment]
Okay, I'll put a little explanation in the README.Debian file.

**Comment by mechanicalamit** [comment]
@barak  With gmi init I had the same problem. I copied the link thrown out by gmi and used it on another machine with google login to authenticate. The google login tries to go back to localhost:8080 with the authenticated response link. I copied that and pasted in the ssh session within elinks (text browser). It worked.

**Comment by barak** [comment]
Thanks! Now I have some actual text for the README.

**Comment by gauteh** [comment]
Can this issue be closed?

**Comment by barak** [comment]
I'm still having an issue where it works, but authenticates, which requires being under a GUI. But if I try again, it wants to re-authenticate. So I can't do a gmi pull without a GUI, or without manually authenticating.

Perhaps this is due to Debian's remarkably ancient google auth python package.

**Comment by gauteh** [comment]
Ok. So it is the same as #258 ?

**Comment by barak** [comment]
Yes, I think so. Need to test the fix proposed there, but the machine I "gmi pull" from is my desktop at work and it's winter break...

**Comment by gauteh** [comment]
Think the remaining issue is fixed
