### ISSUE TITLE
FYI email read in gmail becomes unread in notmuch and gmail upon sync

### ISSUE THREAD

**Issue by borwick** [gauteh/lieer#264]
I am seeing email that I've read in gmail be downloaded as unread by `notmuch new`. This only happens for email that I have received in gmail and read in gmail prior to synchronizing the message for the first time.

### Steps to reproduce
1. receive new email via gmail
2. read the email in gmail
3. run "notmuch new"
4. in notmuch, I see the email but it is marked _unread_.
5. run "notmuch new" again
6. at this point the message in gmail is marked unread, because it was unread in notmuch

If I then read it again via gmail and run "notmuch new" to sync again, then it stays read.

### My configuration

* lieer v1.6
* notmuch 0.37
* Python 3.8.18

`.notmuch/hooks/pre-new`
```
export LD_LIBRARY_PATH=/opt/local/lib/
source ~/.virtualenvs/lieer2/bin/activate
cd ~/Mail
gmi sync
```

### Version bisection
Here's when I see vs. don't see this behavior for recent lieer versions:

| version  |  see this behavior? |
|--------- | ------------------- |
| v1.1     |  No                 |
| v1.3     |  No                 |
| v1.4     |  Yes                |
| v1.5     |  Yes                |
| v1.6     |  Yes                |

**Comment by euglevi** [comment]
I think this is related to #229.

**Comment by gauteh** [comment]
See #229, the issue is probably identified with a workaround for now.
