### ISSUE TITLE
import mbox file from google takeout of gmail

### ISSUE THREAD

**Issue by milahu** [gauteh/lieer#274]
i want to move my emails from gmail servers to my local machine
so i use "google takeout" to export all my emails to a 5GB mbox file

how can i import that mbox file to lieer?

https://notmuchmail.org/getting-started/#index5h2

<blockquote>

Converting Existing mbox to Maildir

The [mb2md](http://batleth.sapienti-sat.org/projects/mb2md/) tool can be used to convert existing mbox files to Maildir.

Beware that the source and destination directory options to mb2md are relative to the user's home directory, not relative to the current working directory.

</blockquote>

will this "just work"?
or does google produce weird mbox files...?

similar issues in similar projects

- https://github.com/thunderbird/import-export-tools-ng/issues/432
- https://github.com/GAM-team/got-your-back/issues/278
- https://github.com/rgladwell/imap-upload/issues/24

**Comment by gauteh** [comment]
Hi,

Currently unlikely to work. Files must have special name to match google id. And lieer still needs to download metadata list of all mail.

Gaute
