### ISSUE TITLE
Sync drafts

### ISSUE THREAD

**Issue by fikovnik** [gauteh/lieer#64]
According to the readme, gmailieer cannot add email. This is somewhat problematic for drafts. I could set up mbsync just for drafts, but I think that would create duplication since once a draft is pushed, gmi sync would add it to its maildir as well.

I'm not familiar with gmail API, but can drafts be somehow supported? If not, is it possible to black list some tags?

**Comment by gauteh** [comment]
The GMail api does support it. But it might be a bit tricky to keep 
track of arbitrary messages added and synced with the draft tag. Since 
they have to be added using the draft-api and not by adding the label. 
It would be easier if the draft message should be added by gmi by some 
call (e.g. `gmi add draft ...file..`), and not by detecting it 
automatically maybe.. otherwise we could keep drafts in a separate 
folder maybe.

What do you mean by blacklist? Not download / upload messages with a 
certain tag? Or ignore the tag. To avoid conflict with new messages just 
don't put the drafts in the gmi/mail dir and they should not be picked 
up by gmi.

**Comment by fikovnik** [comment]
Would it be possible to have the following:

```
xyz/.notmuch
xyz/myname.account/  
xyz/myname.account/mail <- synced by gmi
xyz/myname.account/drafts <- synced by gmi using draft-api - in the next sync they will be in the mail dir
```

notmuch emacs client can be easilly configured to use the drafts folder for drafts.

Yes, I meant ignoring. The problem is that if I do not put them in there and sync them using IMAP, next time they will appear. This is however not that great since it will require yet another tool (like mbsync) and the complete email setup will be a bit too complex.

**Comment by gauteh** [comment]
Filip Krikava writes on februar 26, 2018 15:35:
> Would it be possible to have the following:
> 
> ```
> xyz/.notmuch
> xyz/myname.account/  
> xyz/myname.account/mail <- synced by gmi
> xyz/myname.account/drafts <- synced by gmi using draft-api - in the next sync they will be in the mail dir
> ```
> 
> notmuch emacs client can be easilly configured to use the drafts folder for drafts.
> 
> Yes, I meant ignoring. The problem is that if I do not put them in there and sync them using IMAP, next time they will appear. This is however not that great since it will require yet another tool (like mbsync) and the complete email setup will be a bit too complex.
> 

Yeah, except I don't think they should be duplicated in account/mail.

**Comment by fikovnik** [comment]
I think there is a bit of misunderstanding - imagine I have the drafts and mail folder. I sync the drafts with mbsync. Now, locally I compose a draft mail. The message will be stored in the drafts folder. That message will be then synced with gmail using mbsync - it will be both in the drafts fodlder and on gmail. Next time I run gmi sync - the same message will be copied to the mail folder, won't it? If so then I will have a duplicate, right?

Does it make sense?

**Comment by gauteh** [comment]
Filip Krikava writes on februar 26, 2018 15:42:
> I think there is a bit of misunderstanding - imagine I have the drafts and mail folder. I sync the drafts with mbsync. Now, locally I compose a draft mail. The message will be stored in the drafts folder. That message will be then synced with gmail using mbsync - it will be both in the drafts fodlder and on gmail. Next time I run gmi sync - the same message will be copied to the mail folder, won't it? If so then I will have a duplicate, right?
> 
> Does it make sense?
> 
> 

Yup, I was thinking about the future where we have a gmi add-draft 
method.

**Comment by gauteh** [comment]
Closing, not a (personal) priority atm. Happy to review code.

**Comment by laur89** [comment]
@fikovnik what solution did you eventually choose?

**Comment by fikovnik** [comment]
I don't use it anymore
