### ISSUE TITLE
suggest notmuch ignore pattern is invalid

### ISSUE THREAD

**Issue by dtzWill** [gauteh/lieer#94]
Concretely, using the provided `ignore=*.json;` didn't result in notmuch skipping json files, which it would complain about when executing `notmuch new`.

While investigating, it seems:

* Trailing semicolon should be removed-- as-is it encodes the list of patterns: `[ "*.json" "" ]` with the second pattern being empty string which is invalid.
* No mention of support for globbing as the pattern suggests.  0.26 introduced support for regex, but the provided pattern is neither delimited with slashes as required nor is it a valid regex (closest would be `.*\.json` or so).

While I quite possibly am doing something wrong since this seems to work for everyone else (?),
the following seems to work but may be incomplete or imprecise-- I'm still trying to get my initial sync to complete so I mostly wanted something good enough to be sure notmuch wasn't interfering with files it shouldn't.

Pattern that works but probably should be reviewed: `/.*.json$/` (usage would be `ignore=/.*.json$/`).

Actually looking at it now I wasn't able to sort out how to escape a period so just punted on that now--originally attempting things like `/\..*\.json$/`.

----

On the subject, ignoring json files seems insufficient? In my limited usage so far I've found gmailieer creates other files resulting in ignoring the following as well:

`/.*.json$/;.gmailieer.json;.gmailieer.json.bak;.lock`

Apologies if I'm missing something, otherwise hope this helps improve things for folks! Thanks!

**Comment by gauteh** [comment]
Yes, these files keep popping up on the unprocessed list. Notmuch 
detects them and their change, but also correctly identifies them as 
non-emails. Feel free to make PR with the correct value. 

> On the subject, ignoring json files seems insufficient? In my limited 
> usage so far I've found gmailieer creates other files resulting in 
> ignoring the following as well:
> 
> `/.*.json$/;.gmailieer.json;.gmailieer.json.bak;.lock`

In the above, you probably do not need the first entry right?

**Comment by dtzWill** [comment]
Well I wanted it there because I have other json files (`.credentials.gmailieer.json` and `client_id.json`) and wasn't sure if there would be more.

FWIW I think this regex is wrong in that it may cause notmuch to ignore mail if the mail (unlikely but AFAIK possible) filename itself ends with 'json'.  Or maybe that's not possible, but thought I'd mention it.

**Comment by gauteh** [comment]
Will Dietz writes on October 10, 2018 19:07:
> Well I wanted it there because I have other json files (`.credentials.gmailieer.json` and `client_id.json`) and wasn't sure if there would be more.

Oh, right. Forgot about those. In that case the .gmailieer.json is not 
necessary. 

> FWIW I think this regex is wrong in that it may cause notmuch to ignore mail if the mail (unlikely but AFAIK possible) filename itself ends with 'json'.  Or maybe that's not possible, but thought I'd mention it.

Theoretically, yes. That is what I've been trying to accomplish with 
the current pattern.

**Comment by nickurak** [comment]
The suggestions here fail to escape the `.` in the filename, meaning it would ignore mail files named `This_legit_message_has_my_json` (since the `.` would match the `_`)

With that correction, and wanting multiple patterns, here's what looks right to me:

`ignore=/.*[.](json|lock|bak)$/`

**Comment by gauteh** [comment]
Has the latest suggestion by @nickurak been tested? Do you want to submit a patch for that?

**Comment by nickurak** [comment]
It's been tested in the sense that it's what I use :)

**Comment by gauteh** [comment]
Great 🙂

tor. 29. aug. 2019, 17:22 skrev Jeremy Nickurak <notifications@github.com>:
